In [ ]:
import pandas as pd

In [ ]:
df =pd.read_csv('/content/Luxury_Housing_Bangalore.csv')

In [ ]:
data = df.copy()

In [ ]:
data.head()

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  object
 1   Micro_Market          101000 non-null  object
 2   Project_Name          101000 non-null  object
 3   Developer_Name        101000 non-null  object
 4   Unit_Size_Sqft        90954 non-null   float64
 5   Configuration         101000 non-null  object
 6   Ticket_Price_Cr       90981 non-null   object
 7   Transaction_Type      101000 non-null  object
 8   Buyer_Type            101000 non-null  object
 9   Purchase_Quarter      101000 non-null  object
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         90910 non-null   float64
 12  Possession_Status     101000 non-null  object
 13  Sales_Channel         101000 non-null  object
 14  NRI_Buyer             101000 non-null  object
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   object
dtypes: float64(4), int64(1), object(13)
memory usage: 13.9+ MB

In [ ]:
data.describe()

,Unit_Size_Sqft,Connectivity_Score,Amenity_Score,Locality_Infra_Score,Avg_Traffic_Time_Min
count,90954.000000,101000.000000,90910.000000,101000.000000,101000.000000
mean,5972.274765,6.992619,7.503663,7.498426,67.182921
std,1783.397836,1.731757,1.440758,1.443128,30.271611
min,-1.000000,4.000031,5.000224,5.000013,15.000000
25%,4477.250000,5.494526,6.260329,6.247954,41.000000
50%,5990.000000,6.985805,7.499123,7.495614,67.000000
75%,7497.000000,8.490000,8.752207,8.749824,93.000000
max,8999.000000,9.999970,9.999865,9.999956,119.000000

In [ ]:
data.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft          10046
Configuration               0
Ticket_Price_Cr         10019
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10090
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18287
dtype: int64

In [ ]:
data.duplicated().sum()

np.int64(1000)

In [ ]:
data[data.duplicated()].head()

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
100000,PROP036224,DOMLUR,Project_223,Embassy,4608.0,5bhk+,6.567529360287568,Secondary,HNI,2024-09-30,8.810723,8.286767,Launch,Broker,yes,9.291593,74,NaN
100001,PROP018298,Domlur,Project_297,Tata Housing,7455.0,5BHK+,NaN,Primary,Other,2024-12-31,4.173285,8.759681,Launch,Online,yes,8.447694,28,Great view from 15th floor.
100002,PROP084496,rajajinagar,Project_495,Prestige,3778.0,4bhk,12.568326856995945,Secondary,NRI,2023-12-31,9.366757,9.049776,Under construction,Broker,no,9.806097,92,Excellent location!
100003,PROP065620,DOMLUR,Project_119,Brigade,NaN,4BHK,₹12.59 Cr,Secondary,Startup Founder,2024-12-31,7.266646,5.718584,Launch,NRI Desk,yes,5.206301,88,Too far from my office.
100004,PROP088229,WHITEFIELD,Project_228,Total Environment,7458.0,4BHK,13.713149406825654,Secondary,HNI,2023-09-30,7.539427,7.310738,Ready to move,Direct,yes,6.533569,69,Connectivity is poor.

In [ ]:
data[data.duplicated(keep=False)].head(10)

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
50,PROP000051,BELLARY ROAD,Project_50,Total Environment,7385.0,4BHK,8.740334802478952,Primary,HNI,2024-09-30,4.039299,6.756185,Launch,Online,yes,5.314061,34,Will buy after possession.
150,PROP000151,rajajinagar,Project_150,L&T Realty,8678.0,5bhk+,9.321530635745795,Secondary,NRI,2024-12-31,5.638561,5.211055,Launch,Direct,no,5.428077,58,Underpriced for location.
156,PROP000157,Sarjapur Road,Project_156,Sobha,3061.0,5bhk+,16.388946836894448,Primary,HNI,2024-09-30,8.327390,7.945176,Under construction,Online,no,6.626038,79,NaN
232,PROP000233,Mg Road,Project_232,SNN Raj,7640.0,3Bhk,₹12.47 Cr,Secondary,HNI,2023-09-30,4.279519,NaN,Ready to move,Online,yes,7.673679,73,Too far from my office.
324,PROP000325,JAYANAGAR,Project_324,Sobha,4648.0,3Bhk,NaN,Secondary,Startup Founder,2023-12-31,8.252147,7.425450,Launch,NRI Desk,yes,7.080385,34,Great value for money.
485,PROP000486,JAYANAGAR,Project_485,L&T Realty,5258.0,4BHK,9.838687863246108,Primary,Other,2024-09-30,5.677304,6.172892,Launch,NRI Desk,yes,9.784554,76,Underpriced for location.
528,PROP000529,domlur,Project_28,Puravankara,NaN,4BHK,15.649001345874767,Primary,HNI,2025-03-31,4.721722,5.835004,Ready to move,Online,yes,5.151451,70,NaN
537,PROP000538,SARJAPUR ROAD,Project_37,Embassy,3193.0,3BHK,8.329488568637364,Secondary,CXO,2024-03-31,5.137269,9.243307,Ready to move,Direct,yes,6.896502,95,Too far from my office.
542,PROP000543,Rajajinagar,Project_42,Sobha,4664.0,5BHK+,7.523055723745629,Primary,HNI,2024-06-30,4.020615,7.861204,Launch,Direct,yes,7.387999,33,Too far from my office.
556,PROP000557,Electronic City,Project_56,Total Environment,4791.0,3Bhk,9.629589231363465,Primary,CXO,2023-06-30,5.825919,5.545170,Launch,Broker,no,9.328050,93,Great view from 15th floor.

In [ ]:
dup_rows = data[data.duplicated(keep=False)]
dup_rows = dup_rows.sort_values(list(data.columns))

dup_rows.head(50)

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
50,PROP000051,BELLARY ROAD,Project_50,Total Environment,7385.0,4BHK,8.740334802478952,Primary,HNI,2024-09-30,4.039299,6.756185,Launch,Online,yes,5.314061,34,Will buy after possession.
100725,PROP000051,BELLARY ROAD,Project_50,Total Environment,7385.0,4BHK,8.740334802478952,Primary,HNI,2024-09-30,4.039299,6.756185,Launch,Online,yes,5.314061,34,Will buy after possession.
150,PROP000151,rajajinagar,Project_150,L&T Realty,8678.0,5bhk+,9.321530635745795,Secondary,NRI,2024-12-31,5.638561,5.211055,Launch,Direct,no,5.428077,58,Underpriced for location.
100535,PROP000151,rajajinagar,Project_150,L&T Realty,8678.0,5bhk+,9.321530635745795,Secondary,NRI,2024-12-31,5.638561,5.211055,Launch,Direct,no,5.428077,58,Underpriced for location.
156,PROP000157,Sarjapur Road,Project_156,Sobha,3061.0,5bhk+,16.388946836894448,Primary,HNI,2024-09-30,8.327390,7.945176,Under construction,Online,no,6.626038,79,NaN
100209,PROP000157,Sarjapur Road,Project_156,Sobha,3061.0,5bhk+,16.388946836894448,Primary,HNI,2024-09-30,8.327390,7.945176,Under construction,Online,no,6.626038,79,NaN
232,PROP000233,Mg Road,Project_232,SNN Raj,7640.0,3Bhk,₹12.47 Cr,Secondary,HNI,2023-09-30,4.279519,NaN,Ready to move,Online,yes,7.673679,73,Too far from my office.
100704,PROP000233,Mg Road,Project_232,SNN Raj,7640.0,3Bhk,₹12.47 Cr,Secondary,HNI,2023-09-30,4.279519,NaN,Ready to move,Online,yes,7.673679,73,Too far from my office.
324,PROP000325,JAYANAGAR,Project_324,Sobha,4648.0,3Bhk,NaN,Secondary,Startup Founder,2023-12-31,8.252147,7.425450,Launch,NRI Desk,yes,7.080385,34,Great value for money.
100518,PROP000325,JAYANAGAR,Project_324,Sobha,4648.0,3Bhk,NaN,Secondary,Startup Founder,2023-12-31,8.252147,7.425450,Launch,NRI Desk,yes,7.080385,34,Great value for money.
485,PROP000486,JAYANAGAR,Project_485,L&T Realty,5258.0,4BHK,9.838687863246108,Primary,Other,2024-09-30,5.677304,6.172892,Launch,NRI Desk,yes,9.784554,76,Underpriced for location.
100354,PROP000486,JAYANAGAR,Project_485,L&T Realty,5258.0,4BHK,9.838687863246108,Primary,Other,2024-09-30,5.677304,6.172892,Launch,NRI Desk,yes,9.784554,76,Underpriced for location.
528,PROP000529,domlur,Project_28,Puravankara,NaN,4BHK,15.649001345874767,Primary,HNI,2025-03-31,4.721722,5.835004,Ready to move,Online,yes,5.151451,70,NaN
100782,PROP000529,domlur,Project_28,Puravankara,NaN,4BHK,15.649001345874767,Primary,HNI,2025-03-31,4.721722,5.835004,Ready to move,Online,yes,5.151451,70,NaN
537,PROP000538,SARJAPUR ROAD,Project_37,Embassy,3193.0,3BHK,8.329488568637364,Secondary,CXO,2024-03-31,5.137269,9.243307,Ready to move,Direct,yes,6.896502,95,Too far from my office.
100485,PROP000538,SARJAPUR ROAD,Project_37,Embassy,3193.0,3BHK,8.329488568637364,Secondary,CXO,2024-03-31,5.137269,9.243307,Ready to move,Direct,yes,6.896502,95,Too far from my office.
542,PROP000543,Rajajinagar,Project_42,Sobha,4664.0,5BHK+,7.523055723745629,Primary,HNI,2024-06-30,4.020615,7.861204,Launch,Direct,yes,7.387999,33,Too far from my office.
100154,PROP000543,Rajajinagar,Project_42,Sobha,4664.0,5BHK+,7.523055723745629,Primary,HNI,2024-06-30,4.020615,7.861204,Launch,Direct,yes,7.387999,33,Too far from my office.
556,PROP000557,Electronic City,Project_56,Total Environment,4791.0,3Bhk,9.629589231363465,Primary,CXO,2023-06-30,5.825919,5.545170,Launch,Broker,no,9.328050,93,Great view from 15th floor.
100805,PROP000557,Electronic City,Project_56,Total Environment,4791.0,3Bhk,9.629589231363465,Primary,CXO,2023-06-30,5.825919,5.545170,Launch,Broker,no,9.328050,93,Great view from 15th floor.
613,PROP000614,JP NAGAR,Project_113,Total Environment,NaN,3BHK,13.071092033640811,Secondary,Other,2024-12-31,5.104938,8.158959,Launch,Direct,yes,7.052502,116,Will buy after possession.
100365,PROP000614,JP NAGAR,Project_113,Total Environment,NaN,3BHK,13.071092033640811,Secondary,Other,2024-12-31,5.104938,8.158959,Launch,Direct,yes,7.052502,116,Will buy after possession.
746,PROP000747,Rajajinagar,Project_246,Sobha,6240.0,3bhk,₹13.62 Cr,Primary,CXO,2024-12-31,4.241946,9.542768,Launch,Direct,yes,9.800737,56,Agent was not responsive.
100124,PROP000747,Rajajinagar,Project_246,Sobha,6240.0,3bhk,₹13.62 Cr,Primary,CXO,2024-12-31,4.241946,9.542768,Launch,Direct,yes,9.800737,56,Agent was not responsive.
809,PROP000810,BANNERGHATTA ROAD,Project_309,SNN Raj,4491.0,5Bhk+,15.415755707184653,Primary,Startup Founder,2024-06-30,4.424362,5.021226,Launch,NRI Desk,no,8.117290,66,Underpriced for location.
100025,PROP000810,BANNERGHATTA ROAD,Project_309,SNN Raj,4491.0,5Bhk+,15.415755707184653,Primary,Startup Founder,2024-06-30,4.424362,5.021226,Launch,NRI Desk,no,8.117290,66,Underpriced for location.
840,PROP000841,SARJAPUR ROAD,Project_340,Godrej,8929.0,5bhk+,12.834072197378319,Secondary,NRI,2024-03-31,4.775206,7.563358,Under construction,Direct,no,9.880900,57,Underpriced for location.
100658,PROP000841,SARJAPUR ROAD,Project_340,Godrej,8929.0,5bhk+,12.834072197378319,Secondary,NRI,2024-03-31,4.775206,7.563358,Under construction,Direct,no,9.880900,57,Underpriced for location.
1274,PROP001275,bellary road,Project_274,Tata Housing,3807.0,3Bhk,11.754923866125528,Secondary,NRI,2023-06-30,4.507650,5.999728,Launch,Online,yes,5.279252,47,Great view from 15th floor.
100034,PROP001275,bellary road,Project_274,Tata Housing,3807.0,3Bhk,11.754923866125528,Secondary,NRI,2023-06-30,4.507650,5.999728,Launch,Online,yes,5.279252,47,Great view from 15th floor.
1592,PROP001593,Mg Road,Project_92,L&T Realty,3300.0,3BHK,NaN,Secondary,Other,2023-06-30,6.894093,9.902051,Launch,Online,yes,9.859742,68,Loved the amenities!
100262,PROP001593,Mg Road,Project_92,L&T Realty,3300.0,3BHK,NaN,Secondary,Other,2023-06-30,6.894093,9.902051,Launch,Online,yes,9.859742,68,Loved the amenities!
1613,PROP001614,KANAKAPURA ROAD,Project_113,Total Environment,5286.0,4BHK,8.571061494359649,Secondary,HNI,2025-03-31,8.670118,9.476185,Under construction,Direct,no,5.693320,42,Agent was not responsive.
100929,PROP001614,KANAKAPURA ROAD,Project_113,Total Environment,5286.0,4BHK,8.571061494359649,Secondary,HNI,2025-03-31,8.670118,9.476185,Under construction,Direct,no,5.693320,42,Agent was not responsive.
1637,PROP001638,WHITEFIELD,Project_137,L&T Realty,8029.0,3bhk,9.828196581103965,Primary,CXO,2023-09-30,4.959752,8.392904,Launch,NRI Desk,yes,6.256429,57,Great view from 15th floor.
100230,PROP001638,WHITEFIELD,Project_137,L&T Realty,8029.0,3bhk,9.828196581103965,Primary,CXO,2023-09-30,4.959752,8.392904,Launch,NRI Desk,yes,6.256429,57,Great view from 15th floor.
1696,PROP001697,Hebbal,Project_196,Sobha,NaN,4BHK,13.971108693713509,Primary,HNI,2024-12-31,9.411543,5.417414,Under construction,NRI Desk,no,6.979583,59,Excellent location!
100931,PROP001697,Hebbal,Project_196,Sobha,NaN,4BHK,13.971108693713509,Primary,HNI,2024-12-31,9.411543,5.417414,Under construction,NRI Desk,no,6.979583,59,Excellent location!
1780,PROP001781,HENNUR ROAD,Project_280,Prestige,5576.0,3BHK,₹8.22 Cr,Primary,NRI,2024-09-30,9.300760,9.090683,Launch,NRI Desk,yes,9.104885,50,Will buy after possession.
100392,PROP001781,HENNUR ROAD,Project_280,Prestige,5576.0,3BHK,₹8.22 Cr,Primary,NRI,2024-09-30,9.300760,9.090683,Launch,NRI Desk,yes,9.104885,50,Will buy after possession.
1807,PROP001808,BANNERGHATTA ROAD,Project_307,Godrej,8730.0,3bhk,9.351008192966512,Secondary,NRI,2024-06-30,6.537026,NaN,Ready to move,Online,no,7.644891,24,Agent was not responsive.
100752,PROP001808,BANNERGHATTA ROAD,Project_307,Godrej,8730.0,3bhk,9.351008192966512,Secondary,NRI,2024-06-30,6.537026,NaN,Ready to move,Online,no,7.644891,24,Agent was not responsive.
1954,PROP001955,koramangala,Project_454,Puravankara,8203.0,3bhk,15.744577991260858,Primary,Startup Founder,2024-06-30,8.187327,8.659648,Ready to move,Broker,yes,9.558379,28,Loved the amenities!
100090,PROP001955,koramangala,Project_454,Puravankara,8203.0,3bhk,15.744577991260858,Primary,Startup Founder,2024-06-30,8.187327,8.659648,Ready to move,Broker,yes,9.558379,28,Loved the amenities!
2183,PROP002184,JAYANAGAR,Project_183,SNN Raj,3668.0,3bhk,17.581733165220815,Primary,Startup Founder,2023-06-30,5.346389,6.563423,Under construction,NRI Desk,yes,7.272698,53,Connectivity is poor.
100478,PROP002184,JAYANAGAR,Project_183,SNN Raj,3668.0,3bhk,17.581733165220815,Primary,Startup Founder,2023-06-30,5.346389,6.563423,Under construction,NRI Desk,yes,7.272698,53,Connectivity is poor.
2372,PROP002373,ELECTRONIC CITY,Project_372,L&T Realty,NaN,4Bhk,13.740735035969113,Primary,NRI,2024-06-30,4.358038,5.668517,Under construction,Online,yes,9.554681,18,Connectivity is poor.
100100,PROP002373,ELECTRONIC CITY,Project_372,L&T Realty,NaN,4Bhk,13.740735035969113,Primary,NRI,2024-06-30,4.358038,5.668517,Under construction,Online,yes,9.554681,18,Connectivity is poor.
2490,PROP002491,Rajajinagar,Project_490,Tata Housing,6498.0,5Bhk+,70.0,Primary,NRI,2023-12-31,9.252604,6.265874,Launch,Online,no,5.888873,93,Underpriced for location.
100557,PROP002491,Rajajinagar,Project_490,Tata Housing,6498.0,5Bhk+,70.0,Primary,NRI,2023-12-31,9.252604,6.265874,Launch,Online,no,5.888873,93,Underpriced for location.

In [ ]:
data['Property_ID'].duplicated().sum()

np.int64(1000)

In [ ]:
data=data.drop_duplicates()

In [ ]:
data.duplicated().sum()

np.int64(0)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        90043 non-null   float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       90087 non-null   object
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  object
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         90000 non-null   float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        81901 non-null   object
dtypes: float64(4), int64(1), object(13)
memory usage: 14.5+ MB

In [ ]:
data.head(7)

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
5,PROP000006,YELAHANKA,Project_5,Brigade,4290.0,4bhk,₹9.82 Cr,Secondary,HNI,2023-09-30,7.936068,NaN,Launch,Online,no,5.154027,16,Underpriced for location.
6,PROP000007,Bannerghatta Road,Project_6,Prestige,6776.0,5BHK+,10.896752354445224,Secondary,Other,2025-03-31,8.643117,8.355238,Under construction,Direct,no,9.791550,74,Too far from my office.

In [ ]:
data['Property_ID'].duplicated().sum()

np.int64(0)

In [ ]:
data['Micro_Market'].nunique()

48

In [ ]:
data['Micro_Market'].unique()

array(['Sarjapur Road', 'Indiranagar', 'Bannerghatta Road',
       'bellary road', 'Koramangala', 'YELAHANKA', 'whitefield',
       'sarjapur road', 'JP NAGAR', 'Rajajinagar', 'koramangala',
       'WHITEFIELD', 'indiranagar', 'jayanagar', 'Whitefield', 'DOMLUR',
       'yelahanka', 'Mg Road', 'HENNUR ROAD', 'Jayanagar', 'Domlur',
       'Electronic City', 'Hebbal', 'mg road', 'jp nagar',
       'BANNERGHATTA ROAD', 'MG ROAD', 'KANAKAPURA ROAD', 'HEBBAL',
       'BELLARY ROAD', 'electronic city', 'ELECTRONIC CITY',
       'Bellary Road', 'Hennur Road', 'rajajinagar', 'Kanakapura Road',
       'INDIRANAGAR', 'hennur road', 'kanakapura road', 'domlur',
       'bannerghatta road', 'RAJAJINAGAR', 'hebbal', 'Yelahanka',
       'SARJAPUR ROAD', 'KORAMANGALA', 'Jp Nagar', 'JAYANAGAR'],
      dtype=object)

In [ ]:
data.loc[:, 'Micro_Market'] = data['Micro_Market'].str.strip().str.title()

In [ ]:
data['Micro_Market'].nunique()

16

In [ ]:
data['Micro_Market'].unique()

array(['Sarjapur Road', 'Indiranagar', 'Bannerghatta Road',
       'Bellary Road', 'Koramangala', 'Yelahanka', 'Whitefield',
       'Jp Nagar', 'Rajajinagar', 'Jayanagar', 'Domlur', 'Mg Road',
       'Hennur Road', 'Electronic City', 'Hebbal', 'Kanakapura Road'],
      dtype=object)

In [ ]:
data['Micro_Market'].duplicated().sum()

np.int64(99984)

In [ ]:
data['Developer_Name'].head(10)

0                  RMZ
1          Puravankara
2         Tata Housing
3              Embassy
4              SNN Raj
5              Brigade
6             Prestige
7    Total Environment
8             Prestige
9          Puravankara
Name: Developer_Name, dtype: object

In [ ]:
data['Developer_Name'].nunique()

11

In [ ]:
data['Developer_Name'].unique()

array(['RMZ', 'Puravankara', 'Tata Housing', 'Embassy', 'SNN Raj',
       'Brigade', 'Prestige', 'Total Environment', 'Godrej', 'L&T Realty',
       'Sobha'], dtype=object)

In [ ]:
data['Developer_Name'].duplicated().sum()

np.int64(99989)

In [ ]:
data['Developer_Name'] = data['Developer_Name'].str.strip().str.title()

In [ ]:
data['Developer_Name'] .head(20)

0                   Rmz
1           Puravankara
2          Tata Housing
3               Embassy
4               Snn Raj
5               Brigade
6              Prestige
7     Total Environment
8              Prestige
9           Puravankara
10               Godrej
11              Brigade
12              Snn Raj
13          Puravankara
14           L&T Realty
15           L&T Realty
16              Snn Raj
17           L&T Realty
18    Total Environment
19          Puravankara
Name: Developer_Name, dtype: object

In [ ]:
data['Developer_Name'].unique()

array(['Rmz', 'Puravankara', 'Tata Housing', 'Embassy', 'Snn Raj',
       'Brigade', 'Prestige', 'Total Environment', 'Godrej', 'L&T Realty',
       'Sobha'], dtype=object)

In [ ]:
data['Developer_Name'].nunique()

11

In [ ]:
data['Developer_Name'].value_counts().head(20)

Developer_Name
Snn Raj              9224
Prestige             9224
Brigade              9135
L&T Realty           9126
Godrej               9123
Total Environment    9116
Puravankara          9077
Embassy              9075
Rmz                  9009
Sobha                8958
Tata Housing         8933
Name: count, dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        90043 non-null   float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       90087 non-null   object
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  object
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         90000 non-null   float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        81901 non-null   object
dtypes: float64(4), int64(1), object(13)
memory usage: 16.5+ MB

In [ ]:
data['Unit_Size_Sqft'].head(13)

0     4025.0
1     5760.0
2     7707.0
3     6192.0
4     7147.0
5     4290.0
6     6776.0
7     5763.0
8     5815.0
9     8675.0
10    8872.0
11    8765.0
12    4606.0
Name: Unit_Size_Sqft, dtype: float64

In [ ]:
data['Unit_Size_Sqft'].duplicated().sum()

np.int64(93998)

In [ ]:
data['Unit_Size_Sqft'].isnull().sum()

np.int64(9957)

In [ ]:
data['Unit_Size_Sqft'].describe()

count    90043.000000
mean      5972.040170
std       1783.226054
min         -1.000000
25%       4478.000000
50%       5990.000000
75%       7497.000000
max       8999.000000
Name: Unit_Size_Sqft, dtype: float64

In [ ]:
import numpy as np

In [ ]:
data['Unit_Size_Sqft'] = data['Unit_Size_Sqft'].replace(-1, np.nan)

In [ ]:
data['Unit_Size_Sqft'].describe()

count    89543.000000
mean      6005.393085
std       1731.276595
min       3000.000000
25%       4504.000000
50%       6004.000000
75%       7505.000000
max       8999.000000
Name: Unit_Size_Sqft, dtype: float64

In [ ]:
data['Unit_Size_Sqft'] = data['Unit_Size_Sqft'].fillna(data['Unit_Size_Sqft'].median() )

In [ ]:
data['Unit_Size_Sqft'].isnull().sum()

np.int64(0)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       90087 non-null   object
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  object
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         90000 non-null   float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        81901 non-null   object
dtypes: float64(4), int64(1), object(13)
memory usage: 16.5+ MB

In [ ]:
data.head()

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,Rmz,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,Bellary Road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,Snn Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.

In [ ]:
data['Configuration'].head(15)

0      4bhk
1      3Bhk
2      4bhk
3      3BHK
4      4Bhk
5      4bhk
6     5BHK+
7      3BHK
8      3Bhk
9      4Bhk
10     4BHK
11    5bhk+
12    5BHK+
13     3Bhk
14     4bhk
Name: Configuration, dtype: object

In [ ]:
data['Configuration'].unique()

array(['4bhk', '3Bhk', '3BHK', '4Bhk', '5BHK+', '4BHK', '5bhk+', '5Bhk+',
       '3bhk'], dtype=object)

In [ ]:
data['Configuration'].isnull().sum()

np.int64(0)

In [ ]:
data['Configuration'] = data['Configuration'].str.upper().str.strip()

In [ ]:
data['Configuration'].unique()

array(['4BHK', '3BHK', '5BHK+'], dtype=object)

In [ ]:
data['Luxury_room'] = data['Configuration'].apply(lambda x: 1 if '+' in x else 0)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 19 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       90087 non-null   object
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  object
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         90000 non-null   float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        81901 non-null   object
 18  Luxury_room           100000 non-null  int64
dtypes: float64(4), int64(2), object(13)
memory usage: 17.3+ MB

In [ ]:
import re

In [ ]:
data['Bedrooms'] = data['Configuration'].str.extract(r'(\d+)').astype(int)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       90087 non-null   object
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  object
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         90000 non-null   float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        81901 non-null   object
 18  Luxury_room           100000 non-null  int64
 19  Bedrooms              100000 non-null  int64
dtypes: float64(4), int64(3), object(13)
memory usage: 18.0+ MB

In [ ]:
data['Ticket_Price_Cr'].head(30)

0     12.750846039118798
1     16.292151871065954
2     10.517724412961911
3      9.396367494232896
4     15.345392444511946
5               ₹9.82 Cr
6     10.896752354445224
7      9.357538943683888
8     12.299449409872416
9      9.193310278863123
10    15.221823819949362
11     7.384787238631023
12    11.042463301181789
13    15.166285271789972
14    13.851563178884089
15                  70.0
16     9.750864804838619
17     9.045289663266425
18     7.623657466155216
19     9.627966273140629
20    10.804414932112591
21              ₹8.68 Cr
22     7.901275335746435
23             ₹13.11 Cr
24             ₹13.64 Cr
25    11.600771718968296
26                   NaN
27    12.055118415680276
28     10.99341907034267
29    12.721005513628256
Name: Ticket_Price_Cr, dtype: object

In [ ]:
data['Ticket_Price_Cr'].nunique()

72854

In [ ]:
data['Ticket_Price_Cr'].unique()

array(['12.750846039118798', '16.292151871065954', '10.517724412961911',
       ..., '13.730178633219271', '10.363988981166342',
       '10.415616832095246'], dtype=object)

In [ ]:
data['Ticket_Price_Cr'].isnull().sum()

np.int64(9913)

In [ ]:
data['Ticket_Price_Cr'] = data['Ticket_Price_Cr'].astype(str)

In [ ]:
data['Ticket_Price_Cr'] = data['Ticket_Price_Cr'].str.replace('₹', '').str.replace('Cr', '').str.strip()

In [ ]:
data['Ticket_Price_Cr'] = pd.to_numeric(data['Ticket_Price_Cr'], errors='coerce')

In [ ]:
data['Ticket_Price_Cr'].describe()

count    90087.000000
mean        12.719069
std          7.670383
min         -1.420000
25%         10.010969
50%         12.038456
75%         14.097009
max        100.000000
Name: Ticket_Price_Cr, dtype: float64

In [ ]:
data['Ticket_Price_Cr'] = data['Ticket_Price_Cr'].replace(-1.42, np.nan)

In [ ]:
data['Ticket_Price_Cr'].describe()

count    90086.000000
mean        12.719226
std          7.670280
min         -0.519437
25%         10.010997
50%         12.038489
75%         14.097025
max        100.000000
Name: Ticket_Price_Cr, dtype: float64

In [ ]:
data.loc[data['Ticket_Price_Cr'] < 0, 'Ticket_Price_Cr'] = np.nan

In [ ]:
data['Ticket_Price_Cr'].describe()

count    90082.000000
mean        12.719806
std          7.669956
min          0.660000
25%         10.011617
50%         12.038619
75%         14.097041
max        100.000000
Name: Ticket_Price_Cr, dtype: float64

In [ ]:
data['Luxury_Price_Flag'] = data['Ticket_Price_Cr'].apply(lambda x: 1 if x > 50 else 0)

In [ ]:
data['Ticket_Price_Cr'] = data['Ticket_Price_Cr'].fillna(data['Ticket_Price_Cr'].median())

In [ ]:
data['Ticket_Price_Cr'].describe()

count    100000.000000
mean         12.652246
std           7.282516
min           0.660000
25%          10.265189
50%          12.038619
75%          13.832409
max         100.000000
Name: Ticket_Price_Cr, dtype: float64

In [ ]:
data['Ticket_Price_Cr'].isnull().sum()

np.int64(0)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 21 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       100000 non-null  float64
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  object
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         90000 non-null   float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        81901 non-null   object
 18  Luxury_room           100000 non-null  int64
 19  Bedrooms              100000 non-null  int64
 20  Luxury_Price_Flag     100000 non-null  int64
dtypes: float64(5), int64(4), object(12)
memory usage: 18.8+ MB

In [ ]:
data['Transaction_Type'].describe()

count      100000
unique          2
top       Primary
freq        50013
Name: Transaction_Type, dtype: object

In [ ]:
data['Transaction_Type'].isnull().sum()

np.int64(0)

In [ ]:
data['Transaction_Type'].nunique()

2

In [ ]:
data['Transaction_Type'].unique()

array(['Primary', 'Secondary'], dtype=object)

In [ ]:
data['Transaction_Type'].head(20)

0       Primary
1       Primary
2       Primary
3       Primary
4     Secondary
5     Secondary
6     Secondary
7     Secondary
8     Secondary
9       Primary
10    Secondary
11    Secondary
12      Primary
13      Primary
14    Secondary
15      Primary
16    Secondary
17    Secondary
18      Primary
19    Secondary
Name: Transaction_Type, dtype: object

In [ ]:
data['Buyer_Type'].describe()

count     100000
unique         5
top          CXO
freq       20127
Name: Buyer_Type, dtype: object

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 21 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       100000 non-null  float64
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  object
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         90000 non-null   float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        81901 non-null   object
 18  Luxury_room           100000 non-null  int64
 19  Bedrooms              100000 non-null  int64
 20  Luxury_Price_Flag     100000 non-null  int64
dtypes: float64(5), int64(4), object(12)
memory usage: 18.8+ MB

In [ ]:
data['Buyer_Type'].head()

0      NRI
1    Other
2      HNI
3      HNI
4      HNI
Name: Buyer_Type, dtype: object

In [ ]:
data['Buyer_Type'].nunique()

5

In [ ]:
data['Buyer_Type'].unique()

array(['NRI', 'Other', 'HNI', 'CXO', 'Startup Founder'], dtype=object)

In [ ]:
data['Buyer_Type'].isnull().sum()

np.int64(0)

In [ ]:
data['Purchase_Quarter'].head()

0    2025-03-31
1    2024-06-30
2    2023-12-31
3    2024-03-31
4    2024-12-31
Name: Purchase_Quarter, dtype: object

In [ ]:
data['Purchase_Quarter'].nunique()

8

In [ ]:
data['Purchase_Quarter'].unique()

array(['2025-03-31', '2024-06-30', '2023-12-31', '2024-03-31',
       '2024-12-31', '2023-09-30', '2024-09-30', '2023-06-30'],
      dtype=object)

In [ ]:
data['Purchase_Quarter'].isnull().sum()

np.int64(0)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 21 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       100000 non-null  float64
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  object
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         90000 non-null   float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        81901 non-null   object
 18  Luxury_room           100000 non-null  int64
 19  Bedrooms              100000 non-null  int64
 20  Luxury_Price_Flag     100000 non-null  int64
dtypes: float64(5), int64(4), object(12)
memory usage: 18.8+ MB

In [ ]:
data['Connectivity_Score'].head()

0    7.990091
1    4.839024
2    8.131315
3    7.501657
4    4.525216
Name: Connectivity_Score, dtype: float64

In [ ]:
data['Connectivity_Score'].nunique()

100000

In [ ]:
data['Connectivity_Score'].unique()

array([7.99009059, 4.83902377, 8.13131488, ..., 6.19334714, 9.43564628,
       5.78629175])

In [ ]:
data['Amenity_Score'].head(10)

0    5.462863
1         NaN
2    8.669227
3    5.720246
4    8.609649
5         NaN
6    8.355238
7    9.565013
8    5.580442
9    7.759907
Name: Amenity_Score, dtype: float64

In [ ]:
data['Amenity_Score'].nunique()

90000

In [ ]:
data['Amenity_Score'].unique()

array([5.46286299,        nan, 8.66922724, ..., 7.48247301, 6.36927632,
       5.28402643])

In [ ]:
data['Amenity_Score'].describe()

count    90000.000000
mean         7.504185
std          1.440567
min          5.000224
25%          6.261394
50%          7.499766
75%          8.752300
max          9.999865
Name: Amenity_Score, dtype: float64

In [ ]:
data['Amenity_Score'].isnull().sum()

np.int64(10000)

In [ ]:
data['Amenity_Score'] = data['Amenity_Score'].fillna(data['Amenity_Score'].median())

In [ ]:
data['Amenity_Score'].isnull().sum()

np.int64(0)

In [ ]:
data['Amenity_Score'].describe()

count    100000.000000
mean          7.503743
std           1.366641
min           5.000224
25%           6.395876
50%           7.499766
75%           8.615671
max           9.999865
Name: Amenity_Score, dtype: float64

In [ ]:
data['Possession_Status'].head()

0                Launch
1    Under construction
2         Ready to move
3         Ready to move
4    Under construction
Name: Possession_Status, dtype: object

In [ ]:
data['Possession_Status'].nunique()

3

In [ ]:
data['Possession_Status'].unique()

array(['Launch', 'Under construction', 'Ready to move'], dtype=object)

In [ ]:
data['Possession_Status'] = data['Possession_Status'].str.strip().str.title()

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 21 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       100000 non-null  float64
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  object
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         100000 non-null  float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        81901 non-null   object
 18  Luxury_room           100000 non-null  int64
 19  Bedrooms              100000 non-null  int64
 20  Luxury_Price_Flag     100000 non-null  int64
dtypes: float64(5), int64(4), object(12)
memory usage: 18.8+ MB

In [ ]:
data['Sales_Channel'].head()

0      Broker
1    NRI Desk
2      Direct
3      Online
4      Broker
Name: Sales_Channel, dtype: object

In [ ]:
data['Sales_Channel'].nunique()

4

In [ ]:
data['Sales_Channel'].unique()

array(['Broker', 'NRI Desk', 'Direct', 'Online'], dtype=object)

In [ ]:
data['Sales_Channel'] = data['Sales_Channel'].str.strip().str.title()

In [ ]:
data['Sales_Channel'].unique()

array(['Broker', 'Nri Desk', 'Direct', 'Online'], dtype=object)

In [ ]:
data['Channel_Type'] = data['Sales_Channel'].replace({
    'Broker': 'Offline',
    'Direct': 'Offline',
    'Online': 'Online',
    'Nri Desk': 'Special'
})

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       100000 non-null  float64
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  object
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         100000 non-null  float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        81901 non-null   object
 18  Luxury_room           100000 non-null  int64
 19  Bedrooms              100000 non-null  int64
 20  Luxury_Price_Flag     100000 non-null  int64
 21  Channel_Type          100000 non-null  object
dtypes: float64(5), int64(4), object(13)
memory usage: 19.6+ MB

In [ ]:
data['Channel_Type'].head(5)

0    Offline
1    Special
2    Offline
3     Online
4    Offline
Name: Channel_Type, dtype: object

In [ ]:
data['NRI_Buyer'].head(20)

0     yes
1      no
2     yes
3     yes
4      no
5      no
6      no
7     yes
8     yes
9     yes
10     no
11     no
12    yes
13    yes
14     no
15     no
16     no
17    yes
18    yes
19    yes
Name: NRI_Buyer, dtype: object

In [ ]:
data['NRI_Buyer'].tail()

99995    yes
99996    yes
99997    yes
99998    yes
99999    yes
Name: NRI_Buyer, dtype: object

In [ ]:
data['NRI_Buyer'].nunique()

2

In [ ]:
data['NRI_Buyer'].unique()

array(['yes', 'no'], dtype=object)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       100000 non-null  float64
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  object
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         100000 non-null  float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        81901 non-null   object
 18  Luxury_room           100000 non-null  int64
 19  Bedrooms              100000 non-null  int64
 20  Luxury_Price_Flag     100000 non-null  int64
 21  Channel_Type          100000 non-null  object
dtypes: float64(5), int64(4), object(13)
memory usage: 19.6+ MB

In [ ]:
data['Locality_Infra_Score'].head(10)

0    9.212491
1    7.723898
2    6.985493
3    6.100929
4    5.312510
5    5.154027
6    9.791550
7    9.054713
8    8.552046
9    8.395691
Name: Locality_Infra_Score, dtype: float64

In [ ]:
data['Locality_Infra_Score'].describe()

count    100000.000000
mean          7.499378
std           1.443286
min           5.000013
25%           6.249147
50%           7.497347
75%           8.751793
max           9.999956
Name: Locality_Infra_Score, dtype: float64

In [ ]:
data['Locality_Infra_Score'].isnull().sum()

np.int64(0)

In [ ]:
data['Avg_Traffic_Time_Min'].head(10)

0     18
1    106
2    113
3    106
4     18
5     16
6     74
7     31
8     68
9     18
Name: Avg_Traffic_Time_Min, dtype: int64

In [ ]:
data['Avg_Traffic_Time_Min'].isnull().sum()

np.int64(0)

In [ ]:
data['Avg_Traffic_Time_Min'].describe()

count    100000.000000
mean         67.188020
std          30.267763
min          15.000000
25%          41.000000
50%          67.000000
75%          93.000000
max         119.000000
Name: Avg_Traffic_Time_Min, dtype: float64

In [ ]:
data['Quick_Access'] = data['Avg_Traffic_Time_Min'].apply(
    lambda x: "Yes" if x <= 40 else "No")

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 23 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       100000 non-null  float64
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  object
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         100000 non-null  float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        81901 non-null   object
 18  Luxury_room           100000 non-null  int64
 19  Bedrooms              100000 non-null  int64
 20  Luxury_Price_Flag     100000 non-null  int64
 21  Channel_Type          100000 non-null  object
 22  Quick_Access          100000 non-null  object
dtypes: float64(5), int64(4), object(14)
memory usage: 20.3+ MB

In [ ]:
data['Buyer_Comments'].head(10)

0         Loved the amenities!
1                          NaN
2    Agent was not responsive.
3          Excellent location!
4      Too far from my office.
5    Underpriced for location.
6      Too far from my office.
7                          NaN
8                          NaN
9      Too far from my office.
Name: Buyer_Comments, dtype: object

In [ ]:
data['Buyer_Comments'].describe()

count                      81901
unique                         9
top       Great value for money.
freq                        9283
Name: Buyer_Comments, dtype: object

In [ ]:
data['Buyer_Comments'].nunique()

9

In [ ]:
data['Buyer_Comments'].unique()

array(['Loved the amenities!', nan, 'Agent was not responsive.',
       'Excellent location!', 'Too far from my office.',
       'Underpriced for location.', 'Will buy after possession.',
       'Great value for money.', 'Connectivity is poor.',
       'Great view from 15th floor.'], dtype=object)

In [ ]:
data['Buyer_Comments'].isnull().sum()

np.int64(18099)

In [ ]:
def clean_buyer_comments(x):
  if pd.isnull(x):
    return "No Comments"
  x = x.lower()

  if any ( word in x for word in ['Loved','Excellent','Great',]):
    return " Possitive"
  elif any( words in x for words in ['not','far','Underpriced','poor']):
    return "Negative"
  else:
    return "Neutral"

data['Buyer_sentiment']=data['Buyer_Comments'].apply(clean_buyer_comments)

In [ ]:
data['Buyer_Comments'] = data['Buyer_Comments'].fillna("No Comments")

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 24 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       100000 non-null  float64
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  object
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         100000 non-null  float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        100000 non-null  object
 18  Luxury_room           100000 non-null  int64
 19  Bedrooms              100000 non-null  int64
 20  Luxury_Price_Flag     100000 non-null  int64
 21  Channel_Type          100000 non-null  object
 22  Quick_Access          100000 non-null  object
 23  Buyer_sentiment       100000 non-null  object
dtypes: float64(5), int64(4), object(15)
memory usage: 21.1+ MB

In [ ]:
data.head()

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,...,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments,Luxury_room,Bedrooms,Luxury_Price_Flag,Channel_Type,Quick_Access,Buyer_sentiment
0,PROP000001,Sarjapur Road,Project_0,Rmz,4025.0,4BHK,12.750846,Primary,NRI,2025-03-31,...,yes,9.212491,18,Loved the amenities!,0,4,0,Offline,Yes,Neutral
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3BHK,16.292152,Primary,Other,2024-06-30,...,no,7.723898,106,No Comments,0,3,0,Special,No,No Comments
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4BHK,10.517724,Primary,HNI,2023-12-31,...,yes,6.985493,113,Agent was not responsive.,0,4,0,Offline,No,Negative
3,PROP000004,Bellary Road,Project_3,Embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,...,yes,6.100929,106,Excellent location!,0,3,0,Online,No,Neutral
4,PROP000005,Koramangala,Project_4,Snn Raj,7147.0,4BHK,15.345392,Secondary,HNI,2024-12-31,...,no,5.312510,18,Too far from my office.,0,4,0,Offline,Yes,Negative

In [ ]:
data['Purchase_Quarter'].describe()

count         100000
unique             8
top       2024-03-31
freq           12635
Name: Purchase_Quarter, dtype: object

In [ ]:
data['Purchase_Quarter'].head(10)

0    2025-03-31
1    2024-06-30
2    2023-12-31
3    2024-03-31
4    2024-12-31
5    2023-09-30
6    2025-03-31
7    2025-03-31
8    2024-03-31
9    2023-09-30
Name: Purchase_Quarter, dtype: object

In [ ]:
data['Purchase_Quarter'] = pd.to_datetime(data['Purchase_Quarter'])

data['Year'] = data['Purchase_Quarter'].dt.year

data['Quarter'] = data['Purchase_Quarter'].dt.quarter

In [ ]:
data['Booking_Status'] = data['Luxury_Price_Flag'].apply(
    lambda x: 'Booked' if x == 1 else 'Not Booked'
)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 27 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       100000 non-null  float64
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  datetime64[ns]
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         100000 non-null  float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        100000 non-null  object
 18  Luxury_room           100000 non-null  int64
 19  Bedrooms              100000 non-null  int64
 20  Luxury_Price_Flag     100000 non-null  int64
 21  Channel_Type          100000 non-null  object
 22  Quick_Access          100000 non-null  object
 23  Buyer_sentiment       100000 non-null  object
 24  Year                  100000 non-null  int32
 25  Quarter               100000 non-null  int32
 26  Booking_Status        100000 non-null  object
dtypes: datetime64[ns](1), float64(5), int32(2), int64(4), object(15)
memory usage: 22.6+ MB

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 27 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       100000 non-null  float64
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  datetime64[ns]
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         100000 non-null  float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        100000 non-null  object
 18  Luxury_room           100000 non-null  int64
 19  Bedrooms              100000 non-null  int64
 20  Luxury_Price_Flag     100000 non-null  int64
 21  Channel_Type          100000 non-null  object
 22  Quick_Access          100000 non-null  object
 23  Buyer_sentiment       100000 non-null  object
 24  Year                  100000 non-null  int32
 25  Quarter               100000 non-null  int32
 26  Booking_Status        100000 non-null  object
dtypes: datetime64[ns](1), float64(5), int32(2), int64(4), object(15)
memory usage: 22.6+ MB

In [ ]:
data['Booking_Status'].head()

0    Not Booked
1    Not Booked
2    Not Booked
3    Not Booked
4    Not Booked
Name: Booking_Status, dtype: object

In [ ]:
data.head()

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,...,Buyer_Comments,Luxury_room,Bedrooms,Luxury_Price_Flag,Channel_Type,Quick_Access,Buyer_sentiment,Year,Quarter,Booking_Status
0,PROP000001,Sarjapur Road,Project_0,Rmz,4025.0,4BHK,12.750846,Primary,NRI,2025-03-31,...,Loved the amenities!,0,4,0,Offline,Yes,Neutral,2025,1,Not Booked
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3BHK,16.292152,Primary,Other,2024-06-30,...,No Comments,0,3,0,Special,No,No Comments,2024,2,Not Booked
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4BHK,10.517724,Primary,HNI,2023-12-31,...,Agent was not responsive.,0,4,0,Offline,No,Negative,2023,4,Not Booked
3,PROP000004,Bellary Road,Project_3,Embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,...,Excellent location!,0,3,0,Online,No,Neutral,2024,1,Not Booked
4,PROP000005,Koramangala,Project_4,Snn Raj,7147.0,4BHK,15.345392,Secondary,HNI,2024-12-31,...,Too far from my office.,0,4,0,Offline,Yes,Negative,2024,4,Not Booked

#sql

In [ ]:
import sqlite3

In [ ]:
conn = sqlite3.connect('housing.db')
cursor = conn.cursor()

In [ ]:
data.to_sql('housing_db', conn, if_exists='replace')

100000

In [ ]:
cursor.execute("""select count(*) from housing_db""")
cursor.fetchall()

[(100000,)]

Market Trends


How have luxury housing bookings changed quarter by quarter across micro-markets?
 → (Line Chart with Quarter on X-axis and Booking_Count on Y-axis, segmented by Micro_Market)

In [ ]:
cursor.execute("""
SELECT Booking_Status, COUNT(*)
FROM housing_db
GROUP BY Booking_Status
""")
print(cursor.fetchall())

[('Booked', 1000), ('Not Booked', 99000)]

In [ ]:
cursor.execute("""DROP TABLE IF EXISTS market_trends;""")
cursor.execute("""
CREATE TABLE market_trends AS
SELECT
    Year,
    Quarter,
    Micro_Market,
    COUNT(*) AS Booking_Count
FROM housing_db
WHERE Luxury_Price_Flag = 1
GROUP BY Year, Quarter, Micro_Market
ORDER BY Year, Quarter;
""")

conn.commit()

In [ ]:
cursor.execute("SELECT * FROM market_trends LIMIT 10")
print(cursor.fetchall())

[(2023, 2, 'Bannerghatta Road', 6), (2023, 2, 'Bellary Road', 8), (2023, 2, 'Domlur', 8), (2023, 2, 'Electronic City', 13), (2023, 2, 'Hebbal', 5), (2023, 2, 'Hennur Road', 11), (2023, 2, 'Indiranagar', 4), (2023, 2, 'Jayanagar', 11), (2023, 2, 'Jp Nagar', 7), (2023, 2, 'Kanakapura Road', 8)]

In [ ]:
df_market = pd.read_sql("SELECT * FROM market_trends", conn)
df_market.to_csv("market_trends.csv", index=False)

Builder Performance


Which builders have the highest total ticket sales and how do they rank in terms of average ticket size?
 → (Bar Chart or Table showing Builder, Sum(Ticket_Price_Cr), Avg(Ticket_Price_Cr))

In [ ]:
cursor.execute("""DROP TABLE IF EXISTS Builder_Performance;""")
cursor.execute("""CREATE TABLE Builder_Performance AS SELECT Developer_Name, SUM(Ticket_Price_Cr) AS total_sales, AVG(Ticket_Price_Cr) AS avg_price FROM housing_db GROUP BY Developer_Name ORDER BY total_sales DESC""")

conn.commit()

In [ ]:
cursor.execute("""select * from Builder_Performance """ )
cursor.fetchall()

[('Prestige', 116750.19906695702, 12.65722019372908),
 ('Total Environment', 116230.61460226431, 12.750177117405036),
 ('L&T Realty', 116065.3074448357, 12.718091983874173),
 ('Snn Raj', 115809.12769056055, 12.555195976860423),
 ('Godrej', 115789.83056035088, 12.692078325150813),
 ('Puravankara', 114950.29630785463, 12.663908373675733),
 ('Sobha', 114649.88977360948, 12.798603457647854),
 ('Brigade', 114519.13071621676, 12.5363033077413),
 ('Rmz', 114086.56603388174, 12.663621493382367),
 ('Embassy', 113809.17125756045, 12.54095551047498),
 ('Tata Housing', 112564.47671575003, 12.600971310394048)]

In [ ]:
df_Builder_Performance= pd.read_sql("SELECT * FROM Builder_Performance", conn)
df_Builder_Performance.to_csv("Builder_Performance.csv", index=False)

Amenity Impact


Is there a correlation between amenity score and booking success rate?
 → (Scatter plot: Amenity_Score vs Booking_Conversion_Rate, with bubble size by Project Count)

In [ ]:
data['Amenity_Score'].head()

0    5.462863
1    7.499766
2    8.669227
3    5.720246
4    8.609649
Name: Amenity_Score, dtype: float64

In [ ]:
data['Booking_Status'].head(20)

0     Not Booked
1     Not Booked
2     Not Booked
3     Not Booked
4     Not Booked
5     Not Booked
6     Not Booked
7     Not Booked
8     Not Booked
9     Not Booked
10    Not Booked
11    Not Booked
12    Not Booked
13    Not Booked
14    Not Booked
15        Booked
16    Not Booked
17    Not Booked
18    Not Booked
19    Not Booked
Name: Booking_Status, dtype: object

In [ ]:
data['Booking_Status'].unique()

array(['Not Booked', 'Booked'], dtype=object)

In [ ]:
cursor.execute("""DROP TABLE IF EXISTS Amenity_relation;""")
cursor.execute("""CREATE TABLE amenity_relation AS
SELECT
    Micro_Market,
    AVG(Amenity_Score) AS Amenity_Score,
    CAST(SUM(CASE
        WHEN Booking_Status = 'Booked' THEN 1
        ELSE 0
    END) AS FLOAT) / COUNT(*) AS Booking_Conversion,
    COUNT(*) AS Total_Projects
FROM housing_db
GROUP BY Micro_Market;""")
conn.commit()

In [ ]:
cursor.execute("SELECT * FROM Amenity_relation LIMIT 10")
print(cursor.fetchall())

[('Bannerghatta Road', 7.515912900752493, 0.010511452776906181, 6374), ('Bellary Road', 7.497675806064223, 0.008688656476267096, 6215), ('Domlur', 7.4971949109809275, 0.009383594887558647, 6181), ('Electronic City', 7.484660276306794, 0.009175788795878943, 6212), ('Hebbal', 7.492835859405508, 0.01069345430978613, 6172), ('Hennur Road', 7.495700050389511, 0.01006820396232543, 6158), ('Indiranagar', 7.526894167715534, 0.010218745010378413, 6263), ('Jayanagar', 7.512129577455585, 0.010189684903589905, 6379), ('Jp Nagar', 7.503302359128331, 0.009414718343009571, 6373), ('Kanakapura Road', 7.518320453832908, 0.009783480352846832, 6235)]

In [ ]:
df_amenity_relation = pd.read_sql("SELECT * FROM Amenity_relation", conn)
df_amenity_relation.to_csv("amenity_relation.csv", index=False)

Booking Conversion


Which micro-markets have the highest and lowest booking conversion rates?
 → (Stacked Column Chart: Micro_Market with % Booking_Status as stacked sections)

In [ ]:
data.info()
data.head()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 27 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       100000 non-null  float64
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  datetime64[ns]
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         100000 non-null  float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        100000 non-null  object
 18  Luxury_room           100000 non-null  int64
 19  Bedrooms              100000 non-null  int64
 20  Luxury_Price_Flag     100000 non-null  int64
 21  Channel_Type          100000 non-null  object
 22  Quick_Access          100000 non-null  object
 23  Buyer_sentiment       100000 non-null  object
 24  Year                  100000 non-null  int32
 25  Quarter               100000 non-null  int32
 26  Booking_Status        100000 non-null  object
dtypes: datetime64[ns](1), float64(5), int32(2), int64(4), object(15)
memory usage: 22.6+ MB

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,...,Buyer_Comments,Luxury_room,Bedrooms,Luxury_Price_Flag,Channel_Type,Quick_Access,Buyer_sentiment,Year,Quarter,Booking_Status
0,PROP000001,Sarjapur Road,Project_0,Rmz,4025.0,4BHK,12.750846,Primary,NRI,2025-03-31,...,Loved the amenities!,0,4,0,Offline,Yes,Neutral,2025,1,Not Booked
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3BHK,16.292152,Primary,Other,2024-06-30,...,No Comments,0,3,0,Special,No,No Comments,2024,2,Not Booked
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4BHK,10.517724,Primary,HNI,2023-12-31,...,Agent was not responsive.,0,4,0,Offline,No,Negative,2023,4,Not Booked
3,PROP000004,Bellary Road,Project_3,Embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,...,Excellent location!,0,3,0,Online,No,Neutral,2024,1,Not Booked
4,PROP000005,Koramangala,Project_4,Snn Raj,7147.0,4BHK,15.345392,Secondary,HNI,2024-12-31,...,Too far from my office.,0,4,0,Offline,Yes,Negative,2024,4,Not Booked

In [ ]:
cursor.execute("""DROP TABLE IF EXISTS Conversion_rates;""")
cursor.execute("""
CREATE TABLE Conversion_rates AS
SELECT
    Micro_Market,

    COUNT(*) AS Total,

    SUM(CASE
        WHEN Booking_Status = 'Booked' THEN 1
        ELSE 0
    END) AS Booked,
    SUM(CASE
        WHEN Booking_Status = 'Not Booked' THEN 1
        ELSE 0
    END) AS Not_Booked,

    CAST(SUM(CASE
        WHEN Booking_Status = 'Booked' THEN 1
        ELSE 0
    END) AS FLOAT) / COUNT(*) AS Conversion_Rate

FROM housing_db

GROUP BY Micro_Market

ORDER BY Conversion_Rate DESC;
""")

In [ ]:
cursor.execute("SELECT * FROM Conversion_rates")
rows = cursor.fetchall()

for row in rows:
    print(row)

('Sarjapur Road', 6373, 73, 6300, 0.011454573983994978)
('Hebbal', 6172, 66, 6106, 0.01069345430978613)
('Yelahanka', 6213, 66, 6147, 0.010622887493964268)
('Bannerghatta Road', 6374, 67, 6307, 0.010511452776906181)
('Indiranagar', 6263, 64, 6199, 0.010218745010378413)
('Whitefield', 6268, 64, 6204, 0.01021059349074665)
('Jayanagar', 6379, 65, 6314, 0.010189684903589905)
('Rajajinagar', 6207, 63, 6144, 0.01014983083615273)
('Hennur Road', 6158, 62, 6096, 0.01006820396232543)
('Koramangala', 6093, 60, 6033, 0.009847365829640572)
('Kanakapura Road', 6235, 61, 6174, 0.009783480352846832)
('Mg Road', 6284, 60, 6224, 0.009548058561425843)
('Jp Nagar', 6373, 60, 6313, 0.009414718343009571)
('Domlur', 6181, 58, 6123, 0.009383594887558647)
('Electronic City', 6212, 57, 6155, 0.009175788795878943)
('Bellary Road', 6215, 54, 6161, 0.008688656476267096)

In [ ]:
df_Conversion_rates= pd.read_sql("SELECT * FROM Conversion_rates", conn)
df_Conversion_rates.to_csv("Conversion_rates.csv", index=False)

Configuration Demand


What are the most in-demand housing configurations (e.g., 3BHK, 4BHK)?
 → (Pie Chart or Donut Chart of Configuration vs Booking Count)

In [ ]:
cursor.execute("""DROP TABLE IF EXISTS Configuration_Demand;""")
cursor.execute(""" CREATE TABLE Configuration_Demand AS
SELECT Configuration, SUM(CASE WHEN Booking_Status ='Booked' THEN 1 ELSE 0 END ) AS Booked_Count
FROM housing_db
GROUP BY Configuration
ORDER BY Booked_Count DESC;
""")

In [ ]:
cursor.execute("""SELECT * FROM Configuration_Demand""" )

In [ ]:
df_Configuration_Demand= pd.read_sql("SELECT * FROM Configuration_Demand", conn)
df_Configuration_Demand.to_csv("Configuration_Demand.csv", index=False)

Sales Channel Efficiency


Which sales channels contribute most to successful bookings?
 → (100% Stacked Column Chart: Sales_Channel vs Booking_Status distribution)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 27 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       100000 non-null  float64
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  datetime64[ns]
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         100000 non-null  float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        100000 non-null  object
 18  Luxury_room           100000 non-null  int64
 19  Bedrooms              100000 non-null  int64
 20  Luxury_Price_Flag     100000 non-null  int64
 21  Channel_Type          100000 non-null  object
 22  Quick_Access          100000 non-null  object
 23  Buyer_sentiment       100000 non-null  object
 24  Year                  100000 non-null  int32
 25  Quarter               100000 non-null  int32
 26  Booking_Status        100000 non-null  object
dtypes: datetime64[ns](1), float64(5), int32(2), int64(4), object(15)
memory usage: 22.6+ MB

In [ ]:
data[['Sales_Channel', 'Booking_Status']].head()

  Sales_Channel Booking_Status
0        Broker     Not Booked
1      Nri Desk     Not Booked
2        Direct     Not Booked
3        Online     Not Booked
4        Broker     Not Booked

In [ ]:
cursor.execute("""DROP TABLE IF EXISTS Sales_Channel_Efficiency;""")
cursor.execute("""CREATE TABLE Sales_Channel_Efficiency   AS
SELECT 	Sales_Channel  ,
COUNT(*) AS Total_Count,

    SUM(CASE
        WHEN Booking_Status = 'Booked' THEN 1
        ELSE 0
    END) AS Booked_Count,
    SUM(CASE
        WHEN Booking_Status = 'Not Booked' THEN 1
        ELSE 0
    END) AS Not_Booked,

    CAST(SUM(CASE
        WHEN Booking_Status = 'Booked' THEN 1
        ELSE 0
    END) AS FLOAT) / COUNT(*) AS Conversion_Rate

FROM housing_db
GROUP BY Sales_Channel
ORDER BY Conversion_Rate DESC;
""")

conn.commit()

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 27 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       100000 non-null  float64
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  datetime64[ns]
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         100000 non-null  float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        100000 non-null  object
 18  Luxury_room           100000 non-null  int64
 19  Bedrooms              100000 non-null  int64
 20  Luxury_Price_Flag     100000 non-null  int64
 21  Channel_Type          100000 non-null  object
 22  Quick_Access          100000 non-null  object
 23  Buyer_sentiment       100000 non-null  object
 24  Year                  100000 non-null  int32
 25  Quarter               100000 non-null  int32
 26  Booking_Status        100000 non-null  object
dtypes: datetime64[ns](1), float64(5), int32(2), int64(4), object(15)
memory usage: 22.6+ MB

In [ ]:
data[['Developer_Name', 'Year', 'Quarter','Ticket_Price_Cr']].head()

  Developer_Name  Year  Quarter  Ticket_Price_Cr
0            Rmz  2025        1        12.750846
1    Puravankara  2024        2        16.292152
2   Tata Housing  2023        4        10.517724
3        Embassy  2024        1         9.396367
4        Snn Raj  2024        4        15.345392

In [ ]:
df_Sales_Channel_Efficiency= pd.read_sql("SELECT * FROM Sales_Channel_Efficiency", conn)
df_Sales_Channel_Efficiency.to_csv("Sales_Channel_Efficiency.csv", index=False)

Quarterly Builder Contribution


Which builders dominate the market each quarter?
 → (Matrix Table: Rows = Builder, Columns = Quarter, Values = Sum(Ticket_Price_Cr))

In [ ]:
cursor.execute("""DROP TABLE IF EXISTS Quarterly_Builder_Contribution ;""")

cursor.execute("""CREATE TABLE Quarterly_Builder_Contribution  AS
SELECT Developer_Name,	Quarter, SUM(Ticket_Price_Cr) AS Total_sales
FROM housing_db
GROUP BY Developer_Name, Quarter
ORDER BY Quarter, Total_sales DESC;
""")

conn.commit()

In [ ]:
df_Quarterly_Builder_Contribution= pd.read_sql("SELECT * FROM Quarterly_Builder_Contribution", conn)
df_Quarterly_Builder_Contribution.to_csv("Quarterly_Builder_Contribution.csv", index=False)

Possession Status Analysis

How does possession status affect buyer type and booking decisions?
 → (Clustered Column Chart: Possession_Status vs Booking_Status, colored by Buyer_Type)

In [ ]:
data[['Possession_Status','Buyer_Type','NRI_Buyer']].head()

    Possession_Status Buyer_Type NRI_Buyer
0              Launch        NRI       yes
1  Under Construction      Other        no
2       Ready To Move        HNI       yes
3       Ready To Move        HNI       yes
4  Under Construction        HNI        no

In [ ]:
cursor.execute("""DROP TABLE IF EXISTS possession_analysis;""")
cursor.execute("""
CREATE TABLE possession_analysis AS
SELECT
    Possession_Status,
    Buyer_Type,

    COUNT(*) AS Total_Leads,

    SUM(CASE
        WHEN Booking_Status = 'Booked' THEN 1
        ELSE 0
    END) AS Booked_Count,

    SUM(CASE
        WHEN Booking_Status = 'Not Booked' THEN 1
        ELSE 0
    END) AS Not_Booked_Count,

    CAST(SUM(CASE
        WHEN Booking_Status = 'Booked' THEN 1
        ELSE 0
    END) AS FLOAT) / COUNT(*) AS Conversion_Rate

FROM housing_db

GROUP BY Possession_Status, Buyer_Type

ORDER BY Possession_Status, Conversion_Rate DESC;
""")

conn.commit()

In [ ]:
cursor.execute("""SELECT * FROM possession_analysis""")

In [ ]:
df_possession_analysis = pd.read_sql("SELECT * FROM possession_analysis", conn)
display(df_possession_analysis.head())
df_possession_analysis.to_csv("possession_analysis.csv", index=False)

,Possession_Status,Buyer_Type,Total_Leads,Booked_Count,Not_Booked_Count,Conversion_Rate
0,Launch,CXO,6700,81,6619,0.012090
1,Launch,NRI,6673,71,6602,0.010640
2,Launch,HNI,6598,65,6533,0.009851
3,Launch,Startup Founder,6762,66,6696,0.009760
4,Launch,Other,6608,64,6544,0.009685

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 27 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       100000 non-null  float64
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  datetime64[ns]
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         100000 non-null  float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        100000 non-null  object
 18  Luxury_room           100000 non-null  int64
 19  Bedrooms              100000 non-null  int64
 20  Luxury_Price_Flag     100000 non-null  int64
 21  Channel_Type          100000 non-null  object
 22  Quick_Access          100000 non-null  object
 23  Buyer_sentiment       100000 non-null  object
 24  Year                  100000 non-null  int32
 25  Quarter               100000 non-null  int32
 26  Booking_Status        100000 non-null  object
dtypes: datetime64[ns](1), float64(5), int32(2), int64(4), object(15)
memory usage: 22.6+ MB

In [ ]:
data[['Micro_Market','Luxury_Price_Flag']].head()

        Micro_Market  Luxury_Price_Flag
0      Sarjapur Road                  0
1        Indiranagar                  0
2  Bannerghatta Road                  0
3       Bellary Road                  0
4        Koramangala                  0

Geographical Insights


Where are most luxury housing projects concentrated within Bangalore?
 → (Map visualization using Micro_Market or lat/long if available)

In [ ]:
cursor.execute("""DROP TABLE IF EXISTS geographical_insights;""")

cursor.execute("""
CREATE TABLE geographical_insights AS
SELECT
    Micro_Market,

    COUNT(*) AS Total_Projects,

    SUM(CASE
        WHEN Luxury_Price_Flag = 1 THEN 1
        ELSE 0
    END) AS Luxury_Projects

FROM housing_db

GROUP BY Micro_Market
ORDER BY Luxury_Projects DESC;
""")

conn.commit()

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 27 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       100000 non-null  float64
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  datetime64[ns]
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         100000 non-null  float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        100000 non-null  object
 18  Luxury_room           100000 non-null  int64
 19  Bedrooms              100000 non-null  int64
 20  Luxury_Price_Flag     100000 non-null  int64
 21  Channel_Type          100000 non-null  object
 22  Quick_Access          100000 non-null  object
 23  Buyer_sentiment       100000 non-null  object
 24  Year                  100000 non-null  int32
 25  Quarter               100000 non-null  int32
 26  Booking_Status        100000 non-null  object
dtypes: datetime64[ns](1), float64(5), int32(2), int64(4), object(15)
memory usage: 22.6+ MB

In [ ]:
df_geographical_insights= pd.read_sql("SELECT * FROM geographical_insights", conn)
df_geographical_insights.to_csv("geographical_insights.csv", index=False)

Top Performers


Who are the top 5 builders in terms of revenue and booking success?
 → (Card visuals or KPI indicators with drill-through to detailed project list

In [ ]:
cursor.execute("""DROP TABLE IF EXISTS Top_Performers;""")

cursor.execute("""CREATE TABLE Top_Performers AS
SELECT  Developer_Name , SUM(Ticket_Price_Cr) AS Total_Revenue,
SUM(CASE
        WHEN Booking_Status = 'Booked' THEN 1
        ELSE 0
    END) AS Booked_Count,

    CAST(SUM(CASE
        WHEN Booking_Status = 'Booked' THEN 1
        ELSE 0
    END) AS FLOAT) / COUNT(*) AS Conversion_Rate
    FROM housing_db

GROUP BY Developer_Name

ORDER BY Total_Revenue DESC
 """)
conn.commit()

In [ ]:
df_Top_Performers= pd.read_sql("SELECT * FROM Top_Performers", conn)
df_Top_Performers.to_csv("Top_Performers.csv", index=False)