In [9]:
import pandas as pd

In [10]:

df = pd.read_csv(r"D:\project2\Luxury_Housing_Bangalore.csv")

In [11]:
df.head()

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.

In [12]:
data = df.copy()

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  object
 1   Micro_Market          101000 non-null  object
 2   Project_Name          101000 non-null  object
 3   Developer_Name        101000 non-null  object
 4   Unit_Size_Sqft        90954 non-null   float64
 5   Configuration         101000 non-null  object
 6   Ticket_Price_Cr       90981 non-null   object
 7   Transaction_Type      101000 non-null  object
 8   Buyer_Type            101000 non-null  object
 9   Purchase_Quarter      101000 non-null  object
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         90910 non-null   float64
 12  Possession_Status     101000 non-null  object
 13  Sales_Channel         101000 non-null  object
 14  NRI_Buyer             101000 non-null  object
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   object
dtypes: float64(4), int64(1), object(13)
memory usage: 13.9+ MB

In [14]:
data.describe()

,Unit_Size_Sqft,Connectivity_Score,Amenity_Score,Locality_Infra_Score,Avg_Traffic_Time_Min
count,90954.000000,101000.000000,90910.000000,101000.000000,101000.000000
mean,5972.274765,6.992619,7.503663,7.498426,67.182921
std,1783.397836,1.731757,1.440758,1.443128,30.271611
min,-1.000000,4.000031,5.000224,5.000013,15.000000
25%,4477.250000,5.494526,6.260329,6.247954,41.000000
50%,5990.000000,6.985805,7.499123,7.495614,67.000000
75%,7497.000000,8.490000,8.752207,8.749824,93.000000
max,8999.000000,9.999970,9.999865,9.999956,119.000000

In [15]:
data.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft          10046
Configuration               0
Ticket_Price_Cr         10019
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10090
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18287
dtype: int64

In [16]:
data.duplicated().sum()

np.int64(1000)

In [17]:
data[data.duplicated()].head()

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
100000,PROP036224,DOMLUR,Project_223,Embassy,4608.0,5bhk+,6.567529360287568,Secondary,HNI,2024-09-30,8.810723,8.286767,Launch,Broker,yes,9.291593,74,NaN
100001,PROP018298,Domlur,Project_297,Tata Housing,7455.0,5BHK+,NaN,Primary,Other,2024-12-31,4.173285,8.759681,Launch,Online,yes,8.447694,28,Great view from 15th floor.
100002,PROP084496,rajajinagar,Project_495,Prestige,3778.0,4bhk,12.568326856995945,Secondary,NRI,2023-12-31,9.366757,9.049776,Under construction,Broker,no,9.806097,92,Excellent location!
100003,PROP065620,DOMLUR,Project_119,Brigade,NaN,4BHK,₹12.59 Cr,Secondary,Startup Founder,2024-12-31,7.266646,5.718584,Launch,NRI Desk,yes,5.206301,88,Too far from my office.
100004,PROP088229,WHITEFIELD,Project_228,Total Environment,7458.0,4BHK,13.713149406825654,Secondary,HNI,2023-09-30,7.539427,7.310738,Ready to move,Direct,yes,6.533569,69,Connectivity is poor.

In [18]:
data[data.duplicated(keep=False)].head(10)

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
50,PROP000051,BELLARY ROAD,Project_50,Total Environment,7385.0,4BHK,8.740334802478952,Primary,HNI,2024-09-30,4.039299,6.756185,Launch,Online,yes,5.314061,34,Will buy after possession.
150,PROP000151,rajajinagar,Project_150,L&T Realty,8678.0,5bhk+,9.321530635745795,Secondary,NRI,2024-12-31,5.638561,5.211055,Launch,Direct,no,5.428077,58,Underpriced for location.
156,PROP000157,Sarjapur Road,Project_156,Sobha,3061.0,5bhk+,16.388946836894448,Primary,HNI,2024-09-30,8.327390,7.945176,Under construction,Online,no,6.626038,79,NaN
232,PROP000233,Mg Road,Project_232,SNN Raj,7640.0,3Bhk,₹12.47 Cr,Secondary,HNI,2023-09-30,4.279519,NaN,Ready to move,Online,yes,7.673679,73,Too far from my office.
324,PROP000325,JAYANAGAR,Project_324,Sobha,4648.0,3Bhk,NaN,Secondary,Startup Founder,2023-12-31,8.252147,7.425450,Launch,NRI Desk,yes,7.080385,34,Great value for money.
485,PROP000486,JAYANAGAR,Project_485,L&T Realty,5258.0,4BHK,9.838687863246108,Primary,Other,2024-09-30,5.677304,6.172892,Launch,NRI Desk,yes,9.784554,76,Underpriced for location.
528,PROP000529,domlur,Project_28,Puravankara,NaN,4BHK,15.649001345874767,Primary,HNI,2025-03-31,4.721722,5.835004,Ready to move,Online,yes,5.151451,70,NaN
537,PROP000538,SARJAPUR ROAD,Project_37,Embassy,3193.0,3BHK,8.329488568637364,Secondary,CXO,2024-03-31,5.137269,9.243307,Ready to move,Direct,yes,6.896502,95,Too far from my office.
542,PROP000543,Rajajinagar,Project_42,Sobha,4664.0,5BHK+,7.523055723745629,Primary,HNI,2024-06-30,4.020615,7.861204,Launch,Direct,yes,7.387999,33,Too far from my office.
556,PROP000557,Electronic City,Project_56,Total Environment,4791.0,3Bhk,9.629589231363465,Primary,CXO,2023-06-30,5.825919,5.545170,Launch,Broker,no,9.328050,93,Great view from 15th floor.

In [19]:
dup_rows = data[data.duplicated(keep=False)]
dup_rows = dup_rows.sort_values(list(data.columns))

dup_rows.head(50)

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
50,PROP000051,BELLARY ROAD,Project_50,Total Environment,7385.0,4BHK,8.740334802478952,Primary,HNI,2024-09-30,4.039299,6.756185,Launch,Online,yes,5.314061,34,Will buy after possession.
100725,PROP000051,BELLARY ROAD,Project_50,Total Environment,7385.0,4BHK,8.740334802478952,Primary,HNI,2024-09-30,4.039299,6.756185,Launch,Online,yes,5.314061,34,Will buy after possession.
150,PROP000151,rajajinagar,Project_150,L&T Realty,8678.0,5bhk+,9.321530635745795,Secondary,NRI,2024-12-31,5.638561,5.211055,Launch,Direct,no,5.428077,58,Underpriced for location.
100535,PROP000151,rajajinagar,Project_150,L&T Realty,8678.0,5bhk+,9.321530635745795,Secondary,NRI,2024-12-31,5.638561,5.211055,Launch,Direct,no,5.428077,58,Underpriced for location.
156,PROP000157,Sarjapur Road,Project_156,Sobha,3061.0,5bhk+,16.388946836894448,Primary,HNI,2024-09-30,8.327390,7.945176,Under construction,Online,no,6.626038,79,NaN
100209,PROP000157,Sarjapur Road,Project_156,Sobha,3061.0,5bhk+,16.388946836894448,Primary,HNI,2024-09-30,8.327390,7.945176,Under construction,Online,no,6.626038,79,NaN
232,PROP000233,Mg Road,Project_232,SNN Raj,7640.0,3Bhk,₹12.47 Cr,Secondary,HNI,2023-09-30,4.279519,NaN,Ready to move,Online,yes,7.673679,73,Too far from my office.
100704,PROP000233,Mg Road,Project_232,SNN Raj,7640.0,3Bhk,₹12.47 Cr,Secondary,HNI,2023-09-30,4.279519,NaN,Ready to move,Online,yes,7.673679,73,Too far from my office.
324,PROP000325,JAYANAGAR,Project_324,Sobha,4648.0,3Bhk,NaN,Secondary,Startup Founder,2023-12-31,8.252147,7.425450,Launch,NRI Desk,yes,7.080385,34,Great value for money.
100518,PROP000325,JAYANAGAR,Project_324,Sobha,4648.0,3Bhk,NaN,Secondary,Startup Founder,2023-12-31,8.252147,7.425450,Launch,NRI Desk,yes,7.080385,34,Great value for money.
485,PROP000486,JAYANAGAR,Project_485,L&T Realty,5258.0,4BHK,9.838687863246108,Primary,Other,2024-09-30,5.677304,6.172892,Launch,NRI Desk,yes,9.784554,76,Underpriced for location.
100354,PROP000486,JAYANAGAR,Project_485,L&T Realty,5258.0,4BHK,9.838687863246108,Primary,Other,2024-09-30,5.677304,6.172892,Launch,NRI Desk,yes,9.784554,76,Underpriced for location.
528,PROP000529,domlur,Project_28,Puravankara,NaN,4BHK,15.649001345874767,Primary,HNI,2025-03-31,4.721722,5.835004,Ready to move,Online,yes,5.151451,70,NaN
100782,PROP000529,domlur,Project_28,Puravankara,NaN,4BHK,15.649001345874767,Primary,HNI,2025-03-31,4.721722,5.835004,Ready to move,Online,yes,5.151451,70,NaN
537,PROP000538,SARJAPUR ROAD,Project_37,Embassy,3193.0,3BHK,8.329488568637364,Secondary,CXO,2024-03-31,5.137269,9.243307,Ready to move,Direct,yes,6.896502,95,Too far from my office.
100485,PROP000538,SARJAPUR ROAD,Project_37,Embassy,3193.0,3BHK,8.329488568637364,Secondary,CXO,2024-03-31,5.137269,9.243307,Ready to move,Direct,yes,6.896502,95,Too far from my office.
542,PROP000543,Rajajinagar,Project_42,Sobha,4664.0,5BHK+,7.523055723745629,Primary,HNI,2024-06-30,4.020615,7.861204,Launch,Direct,yes,7.387999,33,Too far from my office.
100154,PROP000543,Rajajinagar,Project_42,Sobha,4664.0,5BHK+,7.523055723745629,Primary,HNI,2024-06-30,4.020615,7.861204,Launch,Direct,yes,7.387999,33,Too far from my office.
556,PROP000557,Electronic City,Project_56,Total Environment,4791.0,3Bhk,9.629589231363465,Primary,CXO,2023-06-30,5.825919,5.545170,Launch,Broker,no,9.328050,93,Great view from 15th floor.
100805,PROP000557,Electronic City,Project_56,Total Environment,4791.0,3Bhk,9.629589231363465,Primary,CXO,2023-06-30,5.825919,5.545170,Launch,Broker,no,9.328050,93,Great view from 15th floor.
613,PROP000614,JP NAGAR,Project_113,Total Environment,NaN,3BHK,13.071092033640811,Secondary,Other,2024-12-31,5.104938,8.158959,Launch,Direct,yes,7.052502,116,Will buy after possession.
100365,PROP000614,JP NAGAR,Project_113,Total Environment,NaN,3BHK,13.071092033640811,Secondary,Other,2024-12-31,5.104938,8.158959,Launch,Direct,yes,7.052502,116,Will buy after possession.
746,PROP000747,Rajajinagar,Project_246,Sobha,6240.0,3bhk,₹13.62 Cr,Primary,CXO,2024-12-31,4.241946,9.542768,Launch,Direct,yes,9.800737,56,Agent was not responsive.
100124,PROP000747,Rajajinagar,Project_246,Sobha,6240.0,3bhk,₹13.62 Cr,Primary,CXO,2024-12-31,4.241946,9.542768,Launch,Direct,yes,9.800737,56,Agent was not responsive.
809,PROP000810,BANNERGHATTA ROAD,Project_309,SNN Raj,4491.0,5Bhk+,15.415755707184653,Primary,Startup Founder,2024-06-30,4.424362,5.021226,Launch,NRI Desk,no,8.117290,66,Underpriced for location.
100025,PROP000810,BANNERGHATTA ROAD,Project_309,SNN Raj,4491.0,5Bhk+,15.415755707184653,Primary,Startup Founder,2024-06-30,4.424362,5.021226,Launch,NRI Desk,no,8.117290,66,Underpriced for location.
840,PROP000841,SARJAPUR ROAD,Project_340,Godrej,8929.0,5bhk+,12.834072197378319,Secondary,NRI,2024-03-31,4.775206,7.563358,Under construction,Direct,no,9.880900,57,Underpriced for location.
100658,PROP000841,SARJAPUR ROAD,Project_340,Godrej,8929.0,5bhk+,12.834072197378319,Secondary,NRI,2024-03-31,4.775206,7.563358,Under construction,Direct,no,9.880900,57,Underpriced for location.
1274,PROP001275,bellary road,Project_274,Tata Housing,3807.0,3Bhk,11.754923866125528,Secondary,NRI,2023-06-30,4.507650,5.999728,Launch,Online,yes,5.279252,47,Great view from 15th floor.
100034,PROP001275,bellary road,Project_274,Tata Housing,3807.0,3Bhk,11.754923866125528,Secondary,NRI,2023-06-30,4.507650,5.999728,Launch,Online,yes,5.279252,47,Great view from 15th floor.
1592,PROP001593,Mg Road,Project_92,L&T Realty,3300.0,3BHK,NaN,Secondary,Other,2023-06-30,6.894093,9.902051,Launch,Online,yes,9.859742,68,Loved the amenities!
100262,PROP001593,Mg Road,Project_92,L&T Realty,3300.0,3BHK,NaN,Secondary,Other,2023-06-30,6.894093,9.902051,Launch,Online,yes,9.859742,68,Loved the amenities!
1613,PROP001614,KANAKAPURA ROAD,Project_113,Total Environment,5286.0,4BHK,8.571061494359649,Secondary,HNI,2025-03-31,8.670118,9.476185,Under construction,Direct,no,5.693320,42,Agent was not responsive.
100929,PROP001614,KANAKAPURA ROAD,Project_113,Total Environment,5286.0,4BHK,8.571061494359649,Secondary,HNI,2025-03-31,8.670118,9.476185,Under construction,Direct,no,5.693320,42,Agent was not responsive.
1637,PROP001638,WHITEFIELD,Project_137,L&T Realty,8029.0,3bhk,9.828196581103965,Primary,CXO,2023-09-30,4.959752,8.392904,Launch,NRI Desk,yes,6.256429,57,Great view from 15th floor.
100230,PROP001638,WHITEFIELD,Project_137,L&T Realty,8029.0,3bhk,9.828196581103965,Primary,CXO,2023-09-30,4.959752,8.392904,Launch,NRI Desk,yes,6.256429,57,Great view from 15th floor.
1696,PROP001697,Hebbal,Project_196,Sobha,NaN,4BHK,13.971108693713509,Primary,HNI,2024-12-31,9.411543,5.417414,Under construction,NRI Desk,no,6.979583,59,Excellent location!
100931,PROP001697,Hebbal,Project_196,Sobha,NaN,4BHK,13.971108693713509,Primary,HNI,2024-12-31,9.411543,5.417414,Under construction,NRI Desk,no,6.979583,59,Excellent location!
1780,PROP001781,HENNUR ROAD,Project_280,Prestige,5576.0,3BHK,₹8.22 Cr,Primary,NRI,2024-09-30,9.300760,9.090683,Launch,NRI Desk,yes,9.104885,50,Will buy after possession.
100392,PROP001781,HENNUR ROAD,Project_280,Prestige,5576.0,3BHK,₹8.22 Cr,Primary,NRI,2024-09-30,9.300760,9.090683,Launch,NRI Desk,yes,9.104885,50,Will buy after possession.
1807,PROP001808,BANNERGHATTA ROAD,Project_307,Godrej,8730.0,3bhk,9.351008192966512,Secondary,NRI,2024-06-30,6.537026,NaN,Ready to move,Online,no,7.644891,24,Agent was not responsive.
100752,PROP001808,BANNERGHATTA ROAD,Project_307,Godrej,8730.0,3bhk,9.351008192966512,Secondary,NRI,2024-06-30,6.537026,NaN,Ready to move,Online,no,7.644891,24,Agent was not responsive.
1954,PROP001955,koramangala,Project_454,Puravankara,8203.0,3bhk,15.744577991260858,Primary,Startup Founder,2024-06-30,8.187327,8.659648,Ready to move,Broker,yes,9.558379,28,Loved the amenities!
100090,PROP001955,koramangala,Project_454,Puravankara,8203.0,3bhk,15.744577991260858,Primary,Startup Founder,2024-06-30,8.187327,8.659648,Ready to move,Broker,yes,9.558379,28,Loved the amenities!
2183,PROP002184,JAYANAGAR,Project_183,SNN Raj,3668.0,3bhk,17.581733165220815,Primary,Startup Founder,2023-06-30,5.346389,6.563423,Under construction,NRI Desk,yes,7.272698,53,Connectivity is poor.
100478,PROP002184,JAYANAGAR,Project_183,SNN Raj,3668.0,3bhk,17.581733165220815,Primary,Startup Founder,2023-06-30,5.346389,6.563423,Under construction,NRI Desk,yes,7.272698,53,Connectivity is poor.
2372,PROP002373,ELECTRONIC CITY,Project_372,L&T Realty,NaN,4Bhk,13.740735035969113,Primary,NRI,2024-06-30,4.358038,5.668517,Under construction,Online,yes,9.554681,18,Connectivity is poor.
100100,PROP002373,ELECTRONIC CITY,Project_372,L&T Realty,NaN,4Bhk,13.740735035969113,Primary,NRI,2024-06-30,4.358038,5.668517,Under construction,Online,yes,9.554681,18,Connectivity is poor.
2490,PROP002491,Rajajinagar,Project_490,Tata Housing,6498.0,5Bhk+,70.0,Primary,NRI,2023-12-31,9.252604,6.265874,Launch,Online,no,5.888873,93,Underpriced for location.
100557,PROP002491,Rajajinagar,Project_490,Tata Housing,6498.0,5Bhk+,70.0,Primary,NRI,2023-12-31,9.252604,6.265874,Launch,Online,no,5.888873,93,Underpriced for location.

In [20]:
data['Property_ID'].duplicated().sum()

np.int64(1000)

In [21]:
data=data.drop_duplicates()

In [22]:
data=data.drop_duplicates()

In [23]:
data.head(7)

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
5,PROP000006,YELAHANKA,Project_5,Brigade,4290.0,4bhk,₹9.82 Cr,Secondary,HNI,2023-09-30,7.936068,NaN,Launch,Online,no,5.154027,16,Underpriced for location.
6,PROP000007,Bannerghatta Road,Project_6,Prestige,6776.0,5BHK+,10.896752354445224,Secondary,Other,2025-03-31,8.643117,8.355238,Under construction,Direct,no,9.791550,74,Too far from my office.

In [24]:
data['Property_ID'].duplicated().sum()

np.int64(0)

In [25]:
data['Micro_Market'].nunique()

48

In [26]:
data['Micro_Market'].unique()

array(['Sarjapur Road', 'Indiranagar', 'Bannerghatta Road',
       'bellary road', 'Koramangala', 'YELAHANKA', 'whitefield',
       'sarjapur road', 'JP NAGAR', 'Rajajinagar', 'koramangala',
       'WHITEFIELD', 'indiranagar', 'jayanagar', 'Whitefield', 'DOMLUR',
       'yelahanka', 'Mg Road', 'HENNUR ROAD', 'Jayanagar', 'Domlur',
       'Electronic City', 'Hebbal', 'mg road', 'jp nagar',
       'BANNERGHATTA ROAD', 'MG ROAD', 'KANAKAPURA ROAD', 'HEBBAL',
       'BELLARY ROAD', 'electronic city', 'ELECTRONIC CITY',
       'Bellary Road', 'Hennur Road', 'rajajinagar', 'Kanakapura Road',
       'INDIRANAGAR', 'hennur road', 'kanakapura road', 'domlur',
       'bannerghatta road', 'RAJAJINAGAR', 'hebbal', 'Yelahanka',
       'SARJAPUR ROAD', 'KORAMANGALA', 'Jp Nagar', 'JAYANAGAR'],
      dtype=object)

In [27]:
data.loc[:, 'Micro_Market'] = data['Micro_Market'].str.strip().str.title()

In [28]:
data['Micro_Market'].nunique()
data['Micro_Market'].unique()

array(['Sarjapur Road', 'Indiranagar', 'Bannerghatta Road',
       'Bellary Road', 'Koramangala', 'Yelahanka', 'Whitefield',
       'Jp Nagar', 'Rajajinagar', 'Jayanagar', 'Domlur', 'Mg Road',
       'Hennur Road', 'Electronic City', 'Hebbal', 'Kanakapura Road'],
      dtype=object)

In [29]:
data['Developer_Name'].head(10)
data['Developer_Name'].nunique()
data['Developer_Name'].unique()

array(['RMZ', 'Puravankara', 'Tata Housing', 'Embassy', 'SNN Raj',
       'Brigade', 'Prestige', 'Total Environment', 'Godrej', 'L&T Realty',
       'Sobha'], dtype=object)

In [30]:
data['Developer_Name'].duplicated().sum()
data['Developer_Name'] = data['Developer_Name'].str.strip().str.title()

In [31]:
data['Developer_Name'] .head(20)

0                   Rmz
1           Puravankara
2          Tata Housing
3               Embassy
4               Snn Raj
5               Brigade
6              Prestige
7     Total Environment
8              Prestige
9           Puravankara
10               Godrej
11              Brigade
12              Snn Raj
13          Puravankara
14           L&T Realty
15           L&T Realty
16              Snn Raj
17           L&T Realty
18    Total Environment
19          Puravankara
Name: Developer_Name, dtype: object

In [32]:
data['Developer_Name'].unique()
data['Developer_Name'].nunique()
data['Developer_Name'].value_counts().head(20)

Developer_Name
Snn Raj              9224
Prestige             9224
Brigade              9135
L&T Realty           9126
Godrej               9123
Total Environment    9116
Puravankara          9077
Embassy              9075
Rmz                  9009
Sobha                8958
Tata Housing         8933
Name: count, dtype: int64

In [33]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        90043 non-null   float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       90087 non-null   object
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  object
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         90000 non-null   float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        81901 non-null   object
dtypes: float64(4), int64(1), object(13)
memory usage: 14.5+ MB

In [34]:
data['Unit_Size_Sqft'].head(13)

0     4025.0
1     5760.0
2     7707.0
3     6192.0
4     7147.0
5     4290.0
6     6776.0
7     5763.0
8     5815.0
9     8675.0
10    8872.0
11    8765.0
12    4606.0
Name: Unit_Size_Sqft, dtype: float64

In [35]:
data['Unit_Size_Sqft'].duplicated().sum()
data['Unit_Size_Sqft'].isnull().sum()
data['Unit_Size_Sqft'].describe()

count    90043.000000
mean      5972.040170
std       1783.226054
min         -1.000000
25%       4478.000000
50%       5990.000000
75%       7497.000000
max       8999.000000
Name: Unit_Size_Sqft, dtype: float64

In [36]:
import numpy as np

In [37]:
data['Unit_Size_Sqft'] = data['Unit_Size_Sqft'].replace(-1, np.nan)

In [38]:
data['Unit_Size_Sqft'].describe()

count    89543.000000
mean      6005.393085
std       1731.276595
min       3000.000000
25%       4504.000000
50%       6004.000000
75%       7505.000000
max       8999.000000
Name: Unit_Size_Sqft, dtype: float64

In [39]:
data['Unit_Size_Sqft'] = data['Unit_Size_Sqft'].fillna(data['Unit_Size_Sqft'].median() )

In [40]:
data['Unit_Size_Sqft'].isnull().sum()
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       90087 non-null   object
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  object
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         90000 non-null   float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        81901 non-null   object
dtypes: float64(4), int64(1), object(13)
memory usage: 14.5+ MB

In [41]:
data['Configuration'].head(15)
data['Configuration'].unique()
data['Configuration'].isnull().sum()

np.int64(0)

In [42]:
data['Configuration'] = data['Configuration'].str.upper().str.strip()
data['Configuration'].unique()

array(['4BHK', '3BHK', '5BHK+'], dtype=object)

In [43]:
data['Luxury_room'] = data['Configuration'].apply(lambda x: 1 if '+' in x else 0)
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 19 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       90087 non-null   object
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  object
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         90000 non-null   float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        81901 non-null   object
 18  Luxury_room           100000 non-null  int64
dtypes: float64(4), int64(2), object(13)
memory usage: 15.3+ MB

In [44]:
import re

In [45]:
data['Bedrooms'] = data['Configuration'].str.extract(r'(\d+)').astype(int)

In [46]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       90087 non-null   object
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  object
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         90000 non-null   float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        81901 non-null   object
 18  Luxury_room           100000 non-null  int64
 19  Bedrooms              100000 non-null  int64
dtypes: float64(4), int64(3), object(13)
memory usage: 16.0+ MB

In [47]:
data['Ticket_Price_Cr'].head(20)
data['Ticket_Price_Cr'].nunique()

72854

In [48]:
data['Ticket_Price_Cr'].unique()
data['Ticket_Price_Cr'].isnull().sum()

np.int64(9913)

In [49]:
data['Ticket_Price_Cr'] = data['Ticket_Price_Cr'].astype(str)

In [50]:
data['Ticket_Price_Cr'] = data['Ticket_Price_Cr'].str.replace('₹', '').str.replace('Cr', '').str.strip()
data['Ticket_Price_Cr'] = pd.to_numeric(data['Ticket_Price_Cr'], errors='coerce')

In [51]:
data['Ticket_Price_Cr'].describe()

count    90087.000000
mean        12.719069
std          7.670383
min         -1.420000
25%         10.010969
50%         12.038456
75%         14.097009
max        100.000000
Name: Ticket_Price_Cr, dtype: float64

In [52]:
data['Ticket_Price_Cr'] = data['Ticket_Price_Cr'].replace(-1.42, np.nan)

In [53]:
data['Ticket_Price_Cr'].describe()

count    90086.000000
mean        12.719226
std          7.670280
min         -0.519437
25%         10.010997
50%         12.038489
75%         14.097025
max        100.000000
Name: Ticket_Price_Cr, dtype: float64

In [54]:
data.loc[data['Ticket_Price_Cr'] < 0, 'Ticket_Price_Cr'] = np.nan
data['Ticket_Price_Cr'].describe()

count    90082.000000
mean        12.719806
std          7.669956
min          0.660000
25%         10.011617
50%         12.038619
75%         14.097041
max        100.000000
Name: Ticket_Price_Cr, dtype: float64

In [55]:
data['Luxury_Price_Flag'] = data['Ticket_Price_Cr'].apply(lambda x: 1 if x > 50 else 0)

In [56]:
data['Ticket_Price_Cr'] = data['Ticket_Price_Cr'].fillna(data['Ticket_Price_Cr'].median())
data['Ticket_Price_Cr'].describe()
data['Ticket_Price_Cr'].isnull().sum()

np.int64(0)

In [57]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 21 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       100000 non-null  float64
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  object
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         90000 non-null   float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        81901 non-null   object
 18  Luxury_room           100000 non-null  int64
 19  Bedrooms              100000 non-null  int64
 20  Luxury_Price_Flag     100000 non-null  int64
dtypes: float64(5), int64(4), object(12)
memory usage: 16.8+ MB

In [58]:
data['Transaction_Type'].describe()
data['Transaction_Type'].isnull().sum()

np.int64(0)

In [59]:
data['Transaction_Type'].nunique()
data['Transaction_Type'].unique()
data['Transaction_Type'].head(10)

0      Primary
1      Primary
2      Primary
3      Primary
4    Secondary
5    Secondary
6    Secondary
7    Secondary
8    Secondary
9      Primary
Name: Transaction_Type, dtype: object

In [60]:
data['Buyer_Type'].describe()

count     100000
unique         5
top          CXO
freq       20127
Name: Buyer_Type, dtype: object

In [61]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 21 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       100000 non-null  float64
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  object
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         90000 non-null   float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        81901 non-null   object
 18  Luxury_room           100000 non-null  int64
 19  Bedrooms              100000 non-null  int64
 20  Luxury_Price_Flag     100000 non-null  int64
dtypes: float64(5), int64(4), object(12)
memory usage: 16.8+ MB

In [62]:
data['Buyer_Type'].head()

0      NRI
1    Other
2      HNI
3      HNI
4      HNI
Name: Buyer_Type, dtype: object

In [63]:
data['Buyer_Type'].nunique()
data['Buyer_Type'].unique()
data['Buyer_Type'].isnull().sum()

np.int64(0)

In [64]:
data['Purchase_Quarter'].head()
data['Purchase_Quarter'].nunique()
data['Purchase_Quarter'].unique()

array(['2025-03-31', '2024-06-30', '2023-12-31', '2024-03-31',
       '2024-12-31', '2023-09-30', '2024-09-30', '2023-06-30'],
      dtype=object)

In [65]:
data['Purchase_Quarter'].isnull().sum()
data['Connectivity_Score'].head()
data['Connectivity_Score'].nunique()
data['Connectivity_Score'].unique()

array([7.99009059, 4.83902377, 8.13131488, ..., 6.19334714, 9.43564628,
       5.78629175])

In [66]:
data['Amenity_Score'].head(10)
data['Amenity_Score'].nunique()
data['Amenity_Score'].unique()
data['Amenity_Score'].describe()

count    90000.000000
mean         7.504185
std          1.440567
min          5.000224
25%          6.261394
50%          7.499766
75%          8.752300
max          9.999865
Name: Amenity_Score, dtype: float64

In [67]:
data['Amenity_Score'].isnull().sum()

np.int64(10000)

In [68]:
data['Amenity_Score'] = data['Amenity_Score'].fillna(data['Amenity_Score'].median())

In [69]:
data['Amenity_Score'].isnull().sum()

np.int64(0)

In [70]:
data['Amenity_Score'].describe()

count    100000.000000
mean          7.503743
std           1.366641
min           5.000224
25%           6.395876
50%           7.499766
75%           8.615671
max           9.999865
Name: Amenity_Score, dtype: float64

In [71]:
data['Possession_Status'].head()

0                Launch
1    Under construction
2         Ready to move
3         Ready to move
4    Under construction
Name: Possession_Status, dtype: object

In [72]:
data['Possession_Status'].nunique()
data['Possession_Status'].unique()

array(['Launch', 'Under construction', 'Ready to move'], dtype=object)

In [73]:
data['Possession_Status'] = data['Possession_Status'].str.strip().str.title()

In [74]:
data['Sales_Channel'].head()
data['Sales_Channel'].nunique()
data['Sales_Channel'].unique()

array(['Broker', 'NRI Desk', 'Direct', 'Online'], dtype=object)

In [75]:
data['Sales_Channel'] = data['Sales_Channel'].str.strip().str.title()

In [76]:
data['Sales_Channel'].unique()

array(['Broker', 'Nri Desk', 'Direct', 'Online'], dtype=object)

In [77]:
data['Channel_Type'] = data['Sales_Channel'].replace({
    'Broker': 'Offline',
    'Direct': 'Offline',
    'Online': 'Online',
    'Nri Desk': 'Special'
})

In [78]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       100000 non-null  float64
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  object
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         100000 non-null  float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        81901 non-null   object
 18  Luxury_room           100000 non-null  int64
 19  Bedrooms              100000 non-null  int64
 20  Luxury_Price_Flag     100000 non-null  int64
 21  Channel_Type          100000 non-null  object
dtypes: float64(5), int64(4), object(13)
memory usage: 17.5+ MB

In [79]:
data['Channel_Type'].head(5)
data['NRI_Buyer'].head(20)

0     yes
1      no
2     yes
3     yes
4      no
5      no
6      no
7     yes
8     yes
9     yes
10     no
11     no
12    yes
13    yes
14     no
15     no
16     no
17    yes
18    yes
19    yes
Name: NRI_Buyer, dtype: object

In [80]:
data['NRI_Buyer'].tail()
data['NRI_Buyer'].nunique()
data['NRI_Buyer'].unique()

array(['yes', 'no'], dtype=object)

In [81]:
data['Locality_Infra_Score'].head(10)
data['Locality_Infra_Score'].describe()
data['Locality_Infra_Score'].isnull().sum()

np.int64(0)

In [82]:
data['Avg_Traffic_Time_Min'].head(10)
data['Avg_Traffic_Time_Min'].isnull().sum()

np.int64(0)

In [83]:
data['Avg_Traffic_Time_Min'].describe()

count    100000.000000
mean         67.188020
std          30.267763
min          15.000000
25%          41.000000
50%          67.000000
75%          93.000000
max         119.000000
Name: Avg_Traffic_Time_Min, dtype: float64

In [84]:
data['Quick_Access'] = data['Avg_Traffic_Time_Min'].apply(
    lambda x: "Yes" if x <= 40 else "No")

In [85]:
data['Buyer_Comments'].head(10)
data['Buyer_Comments'].describe()
data['Buyer_Comments'].nunique()

9

In [86]:
data['Buyer_Comments'].unique()
data['Buyer_Comments'].isnull().sum()

np.int64(18099)

In [87]:
def clean_buyer_comments(x):
  if pd.isnull(x):
    return "No Comments"
  x = x.lower()

  if any ( word in x for word in ['loved','excellent','great',]):
    return " Positive"
  elif any( words in x for words in ['not','far','underpriced','poor']):
    return "Negative"
  else:
    return "Neutral"

data['Buyer_sentiment']=data['Buyer_Comments'].apply(clean_buyer_comments)

In [88]:
data['Buyer_Comments'] = data['Buyer_Comments'].fillna("No Comments")

In [89]:
data.head()

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,...,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments,Luxury_room,Bedrooms,Luxury_Price_Flag,Channel_Type,Quick_Access,Buyer_sentiment
0,PROP000001,Sarjapur Road,Project_0,Rmz,4025.0,4BHK,12.750846,Primary,NRI,2025-03-31,...,yes,9.212491,18,Loved the amenities!,0,4,0,Offline,Yes,Positive
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3BHK,16.292152,Primary,Other,2024-06-30,...,no,7.723898,106,No Comments,0,3,0,Special,No,No Comments
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4BHK,10.517724,Primary,HNI,2023-12-31,...,yes,6.985493,113,Agent was not responsive.,0,4,0,Offline,No,Negative
3,PROP000004,Bellary Road,Project_3,Embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,...,yes,6.100929,106,Excellent location!,0,3,0,Online,No,Positive
4,PROP000005,Koramangala,Project_4,Snn Raj,7147.0,4BHK,15.345392,Secondary,HNI,2024-12-31,...,no,5.312510,18,Too far from my office.,0,4,0,Offline,Yes,Negative

In [90]:
data['Purchase_Quarter'].describe()

count         100000
unique             8
top       2024-03-31
freq           12635
Name: Purchase_Quarter, dtype: object

In [91]:
data['Purchase_Quarter'].head(10)

0    2025-03-31
1    2024-06-30
2    2023-12-31
3    2024-03-31
4    2024-12-31
5    2023-09-30
6    2025-03-31
7    2025-03-31
8    2024-03-31
9    2023-09-30
Name: Purchase_Quarter, dtype: object

In [92]:
data['Purchase_Quarter'] = pd.to_datetime(data['Purchase_Quarter'])

data['Year'] = data['Purchase_Quarter'].dt.year

data['Quarter'] = data['Purchase_Quarter'].dt.quarter

In [93]:
data['Booking_Status'] = data['Luxury_Price_Flag'].apply(
    lambda x: 'Booked' if x == 1 else 'Not Booked'
)

In [94]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 27 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       100000 non-null  float64
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  datetime64[ns]
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         100000 non-null  float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        100000 non-null  object
 18  Luxury_room           100000 non-null  int64
 19  Bedrooms              100000 non-null  int64
 20  Luxury_Price_Flag     100000 non-null  int64
 21  Channel_Type          100000 non-null  object
 22  Quick_Access          100000 non-null  object
 23  Buyer_sentiment       100000 non-null  object
 24  Year                  100000 non-null  int32
 25  Quarter               100000 non-null  int32
 26  Booking_Status        100000 non-null  object
dtypes: datetime64[ns](1), float64(5), int32(2), int64(4), object(15)
memory usage: 20.6+ MB

In [95]:
data['Booking_Status'].head()

0    Not Booked
1    Not Booked
2    Not Booked
3    Not Booked
4    Not Booked
Name: Booking_Status, dtype: object

In [96]:
data.head()

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,...,Buyer_Comments,Luxury_room,Bedrooms,Luxury_Price_Flag,Channel_Type,Quick_Access,Buyer_sentiment,Year,Quarter,Booking_Status
0,PROP000001,Sarjapur Road,Project_0,Rmz,4025.0,4BHK,12.750846,Primary,NRI,2025-03-31,...,Loved the amenities!,0,4,0,Offline,Yes,Positive,2025,1,Not Booked
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3BHK,16.292152,Primary,Other,2024-06-30,...,No Comments,0,3,0,Special,No,No Comments,2024,2,Not Booked
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4BHK,10.517724,Primary,HNI,2023-12-31,...,Agent was not responsive.,0,4,0,Offline,No,Negative,2023,4,Not Booked
3,PROP000004,Bellary Road,Project_3,Embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,...,Excellent location!,0,3,0,Online,No,Positive,2024,1,Not Booked
4,PROP000005,Koramangala,Project_4,Snn Raj,7147.0,4BHK,15.345392,Secondary,HNI,2024-12-31,...,Too far from my office.,0,4,0,Offline,Yes,Negative,2024,4,Not Booked

In [97]:
data.to_csv("cleaned_real_estate_data.csv", index=False, )

In [98]:
import os

print(os.getcwd())

C:\Users\jeevi